### DISCUSSION TITLE
Let's See Your Dashboards!

### DISCUSSION THREAD

**Discussion by PRProd** [PRProd/HA-Firemote#129] [Show and tell]
Show us your dashboards!  We are all using Firemote just a little bit differently, and I know that we've all been inspired by looking at what others have created, so upload your dashboard and inspire someone today!

This is one of the views that I use while I'm working on Firemote development.
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/b5fa3194-d211-4ee9-a274-b4ac8e87ee06)

**Comment by PRProd** [comment]
Here are two examples out of several that were posted by a Firemote user in a Facebook group.  https://www.facebook.com/groups/HomeAssistant/permalink/3506479849623360/ Aren't they beautiful?
![348472548_270613045386587_1941815809484259062_n](https://github.com/PRProd/HA-Firemote/assets/25486599/06cbc10d-67dd-4d38-bf57-ceb290f02a0d)
![348547519_267862162301339_1242957216739617912_n](https://github.com/PRProd/HA-Firemote/assets/25486599/67f0fd7a-6d7f-48e1-b784-149090121ef7)

**Reply by andreasbuff** [reply]
Hello, great job. Question: How did you change the remote to Landscape-Mode?

**Reply by PRProd** [reply]
Greetings @andreasbuff!

 _Landscape-Mode_ is simply just a different remote style option that is simple to change.  By default, the Firemote card will choose the remote style that came with your device, but you don't have to use that one on your Home Assistant Firemote card..
 
The remote style can be changed through the Visual Editor or through the Code Editor (YAML):

<br>

### Visual Editor
From inside the Visual Editor, simply find the **Remote Style** dropdown menu, and choose a different style of remote.  

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/b85a0e68-8433-40b7-88fb-3f21555f4e76)
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/5379074b-1477-4e5b-9457-883923ceb75e)

The remote style pictured above is the **App Launcher 2** option.

<br>

### Code Editor
```yaml
type: custom:firemote-card
entity: media_player.fire_tv_192_168_107_88
device_family: amazon-fire
device_type: fire_tv_4_series
compatibility_mode: default
defaultRemoteStyle_override: ''
app_launcher_relative_size: 0
```

The YAML entry that you need to add or change is **defaultRemoteStyle_override**.  A current list of the options can be found in the [README.md](https://github.com/PRProd/HA-Firemote/blob/main/README.md) file under the [YAML Card Setup Options](https://github.com/PRProd/HA-Firemote/blob/main/README.md#yaml-card-setup-options) section.

![image](https://github.com/PRProd/HA-Firemote/assets/25486599/cef2cf1a-ed94-437f-9594-886341f9848f)

In this case, the one you would want to choose is **AL2** which would change the YAML example above to this:

```yaml
type: custom:firemote-card
entity: media_player.fire_tv_192_168_107_88
device_family: amazon-fire
device_type: fire_tv_4_series
compatibility_mode: default
defaultRemoteStyle_override: AL2
app_launcher_relative_size: 0
```

I hope this helps!

**Reply by thos-edison** [reply]
Still a work in progress, but the Firemote looks great sitting next to the on-screen TV. I have lots of real estate to play with, so I have lots of plans. 😁
![DT-w-FMote](https://github.com/PRProd/HA-Firemote/assets/69136067/5417c6a6-feb1-4f8f-860f-b1c33e516cea)

(I'm actually using .onn and Chromecast w/GoogleTV boxes, but found the fire remote more useful.)

**Comment by PRProd** [comment]
A mobile example from @neilimixamo posted here: https://community.home-assistant.io/t/lovelace-firemote-card-remote-controls-for-amazon-fire-android-devices/471038/71
![696d0098128f847a8b240d464c901688af9a1457](https://github.com/PRProd/HA-Firemote/assets/25486599/6014863f-7cb3-4659-a91c-4602fccd4224)

**Comment by neilimixamo** [comment]
Here is the full page popup remote view: 

<details>
<summary>code</summary>

```yaml
title: media_tv_remote
path: media_tv_remote
icon: mdi:remote-tv
theme: Quick Look Mobile
background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(240,243,253,1) 15%)
type: custom:grid-layout
layout:
  margin: -0.5vh 1vh 0vh
  grid-template-columns: auto
  grid-template-rows: min-content
  grid-template-areas: |
    "main"
cards: 
  - type: custom:layout-card # MAIN
    view_layout:
      grid-area: main
    layout_type: custom:vertical-layout
    layout:
      margin: 0vh 0vh 0vh
      padding: 0vh 0.4vh
    cards:
      - type: custom:button-card
        styles:
          card:
            - background: transparent
            - height: 97vh
            - width: 91vw
            - padding: 0px
            - box-shadow: none
            - cursor: none 
            - --mdc-ripple-press-opacity: 0 
          grid:
            - display: flex
            - justify-content: center
            - align-items: flex-end
        tap_action:
          action: navigate
          navigation_path: media_tv
        custom_fields:
          remote:
            card:
              type: custom:firemote-card
              entity: media_player.tv
              device_family: chromecast
              device_type: chromecast-4k
              compatibility_mode: default
              android_tv_remote_entity: remote.tv
              defaultRemoteStyle_override: #'XM2'
              app_launch_1: youtube
              app_launch_2: tivimate
              hide_button_highlights: true
              button_overrides:
                netflix-button:
                  hidden: true
              scale: '100'
            card_mod:
              style: |
                ha-card {
                  width: min-content;
                  padding: 0px;
                }
```
</details>
