### DISCUSSION TITLE
Long press?

### DISCUSSION THREAD

**Discussion by efiniste** [PRProd/HA-Firemote#270] [General]
I don't seem to be able to do a "long" press of the ok/centre button when using Firemote. I use this, for example, to bring up context menus in the YouTube app. Is this not working because it's a "virtual" button now? Is it possible to program one of the app buttons to do a long press?

Thanks,

Steve

**Comment by PRProd** [comment]
Greetings @efiniste!

You are absolutely right.  A longer press on a virtual button in the Firemote card is not something that's easily detected.  Since I can't properly detect them, a long or short press is processed the same way as regular click.  I've looked into detecting a long press event a few times, but I haven't yet pursued it.  Maybe it's time I look at it again?  

In the meantime, perhaps I can help you with a [launcher button customization](https://github.com/PRProd/HA-Firemote#launcher-button-customizations) to give you a working solution while you wait.  What kind of device are you using?

**Reply by mizuxe** [reply]
Please God do this! Especially for the firemote, I have to tap like 100 times to rewind sometimes, or switch to the official app, or there are buttons that don't work at all because of this, like the 1 and 2 button on the Amazon Fire Style 6, you need to press and hold to program these. Or holding the home button can direct you to a menu for your smart home which can be nice w/Alexa.  That said holding the select button is pretty frequently used as well, at least on youtube to add to playlists.  Even if there was just a way to do it once through a service call or something so that I could program those 2 buttons on Style Six. Either way the firemote is probably one of my favorite parts of my HASS dash ever, so whatever you do I'm still incredibly grateful, it just feels like the only glaring hole in the setup.

**Reply by PRProd** [reply]
@mizuxe ~

My apologies, I know it's an inconvenience and I'd like to get it working exactly like the physical remote, but I haven't had the time to focus and solve that issue yet.  I am VERY happy to read that Firemote is one of your favorite parts of your Home Assistant dashboard!  That made my day!  :smile:

Happily, there **ARE** solutions to most of the things you listed:

**1 and 2 buttons on the Amazon Fire Style 6:**
These buttons can be easily programmed to trigger a Home Assistant service call and/or script execution.  Take a look at the [Button Overrides](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#button-overrides) section on the Firemote readme page for full details and examples.  The button names you will need to use are "programmable-one-button" and "programmable-two-button"

**Holding the Select Button:**
If you scroll down further in this discussion, you will see that I have offered solutions for holding the select button for user @efiniste which have worked for him.  I encourage you to read through and/or study how they work to see if you can come up with the proper solution that works in your environment.

**Holding the Home Button (or any others):**
If you are successful with the Select button, you might find that any other button can be done in a similar way.

If you need help making these things work, please let me know and I will be glad to help.  I just need to know specifically what you are hoping to accomplish, and what kind of device you are controlling.

**Reply by mizuxe** [reply]
I'll give this all a go! programming 1 and 2 buttons is such a W, Thank you so much!

**Comment by efiniste** [comment]
HI @PRProd, thanks very much for the quick response. A launcher button would be great. I'm using a Fire TV, device type fire_tv_4_series

Steve

**Comment by PRProd** [comment]
Good news @efiniste!

I have a Fire TV 4 Series in front of me right now, so I put this simple YAML config together, tested it in YouTube, and it works!
```yaml
type: custom:firemote-card
entity: media_player.fire_tv_192_168_107_88
device_family: amazon-fire
device_type: fire_tv_4_series
compatibility_mode: default
custom_launchers:
  - friendly_name: Longpress Select
    label: L Select
    color: red
    background: white
    service: androidtv.adb_command
    target:
      entity_id: media_player.fire_tv_192_168_107_88
    data:
      command: >-
        sendevent /dev/input/event0 1 28 1 && sendevent /dev/input/event0 0 0 0
        && sleep 1 && sendevent /dev/input/event0 1 28 0 && sendevent
        /dev/input/event0 0 0 0
app_launch_1: customlauncher Longpress Select
```
**PLEASE REMEMBER** to replace my TV's entity ID with yours in both places.

**Comment by efiniste** [comment]
@PRProd Thanks Doug. I'm sorry, I made a mistake on the device type. It's actually a fire_stick_4k in the device type, Fire TV Stick 4k (1st Gen - 2018) on the drop down chooser. The button shows fine in my test card but doesn't have any effect on-screen when pressed. All the other buttons work fine so it's got the correct entity configured.

**Comment by PRProd** [comment]
No problem!  Try it this way instead:
```yaml
type: custom:firemote-card
entity: {YOUR ENTITY ID HERE}
device_family: amazon-fire
device_type: fire_stick_4k
compatibility_mode: default
custom_launchers:
  - friendly_name: Longpress Select
    label: L Select
    color: red
    background: white
    service: androidtv.adb_command
    target:
      entity_id: {YOUR ENTITY ID HERE}
    data:
      command: >-
        sendevent /dev/input/event4 1 28 1 && sendevent /dev/input/event4 0 0 0
        && sleep 1 && sendevent /dev/input/event4 1 28 0 && sendevent
        /dev/input/event4 0 0 0
app_launch_1: customlauncher Longpress Select
```

**Comment by efiniste** [comment]
Works perfectly. Thanks very much, Doug.

Steve

**Comment by PRProd** [comment]
That's great news!  Thanks for letting me know!

**Comment by PRProd** [comment]
@efiniste 

Hello again Steve!  Congrats on getting a NVIDIA Shield!  I hope you love it!  I know It is my favorite of all of the devices I've owned and tested.

In response to [your question](https://community.home-assistant.io/t/lovelace-firemote-card-remote-controls-for-amazon-fire-android-devices/471038/135) in the home assistant community discussion board:
> What do I need to change in the “long press” code for the shield? I’ve changed the target entity id but it’s not working so I’m guessing the command is different.

You are absolutely right, the command is different.  

Because of the way the Shield is designed, you will need to use both the ADB integration and the Android TV Remote integration for this solution to work.  I assume you've already set your system up that way, otherwise the lag would be unbearable. 

```YAML
type: custom:firemote-card
entity: {YOUR SHIELD ENTITY ID HERE}
android_tv_remote_entity: {YOUR SHIELD REMOTE ENTITY ID HERE}
device_family: nvidia-shield
device_type: shield-tv-pro-2019
compatibility_mode: default
custom_launchers:
  - friendly_name: Longpress Select
    label: L Select
    color: red
    background: white
    service: remote.send_command
    target:
      entity_id: {YOUR SHIELD REMOTE ENTITY ID HERE}
    data:
      num_repeats: 1
      delay_secs: 0
      command: KEYCODE_DPAD_CENTER
      hold_secs: 1
app_launch_1: customlauncher Longpress Select
app_launch_2: youtube
```
