### DISCUSSION TITLE
Launch app in Apple TV AND start live stream?

### DISCUSSION THREAD

**Discussion by uspino2** [PRProd/HA-Firemote#307] [Q&A] [answered]
### Feature Request

Is there a way to launch the live stream of a TV app in Apple TV? I'm trying to have a button to launch The Tennis Channel app and start the live stream with no interaction. Currently the app offers the regular live TV stream (accesible once you sign in with your cable subscription - tveverywhere) and a few other streams associated to their Plus subscription. 

Thanks.

**Comment by PRProd** [comment]
I've converted this into a Q&A Discussion since this type of feature already exists in Firemote.

The specific thing you are after is called **Deep Links** which the [Apple TV Integration](https://www.home-assistant.io/integrations/apple_tv#launching-apps) does support.  After you work out what the specific Deep Link should be, this type of action can be fulfilled by using a [button override](https://github.com/PRProd/HA-Firemote#button-overrides) or by making your own [custom launcher](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#launcher-button-customizations).

At the moment, I do not know if there is a deep link available to jump to the content you are requesting, and if there is, what that deep link might be.  If I get any spare time in the next few days, I'll see if I can dig into this a little further.  If not, hopefully someone else on this discussion board might be able to chime in and help with that info.

**Reply by PRProd** [reply]
For what it's worth, I just took a look at the Amazon Fire version of the Tennis Channel app, and that version does not appear to support deep linking.  Android packages are a lot easier for me to examine, so I started there

**Comment by PRProd** [comment]
Another option (not recommended because it's error prone - maybe that's OK?) would be to write a script that does something like this:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/e47ba919-8ca1-46e5-bb74-ec1ee757e1ad)
```YAML
alias: Tennis-test
sequence:
  - service: media_player.select_source
    target:
      entity_id: media_player.apple_tv_4k_2nd_gen
    data:
      source: Tennis Channel
    alias: Open Tennis Channel App
    enabled: true
  - alias: Click BACK many times to reset the Tennis Channel App
    service: remote.send_command
    target:
      entity_id: remote.apple_tv_4k_2nd_gen
    data:
      delay_secs: 0.4
      hold_secs: 0
      num_repeats: 6
      command: home
  - alias: Open Home App
    service: remote.send_command
    target:
      entity_id: remote.apple_tv_4k_2nd_gen
    data:
      num_repeats: 1
      delay_secs: 0
      hold_secs: 0
      command: top_menu
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
    enabled: true
  - service: media_player.select_source
    target:
      entity_id: media_player.apple_tv_4k_2nd_gen
    data:
      source: Tennis Channel
    alias: Open Tennis Channel App
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - alias: Click DOWN twice
    service: remote.send_command
    target:
      entity_id: remote.apple_tv_4k_2nd_gen
    data:
      delay_secs: 0.4
      hold_secs: 0
      command: down
      num_repeats: 2
  - service: remote.send_command
    target:
      entity_id: remote.apple_tv_4k_2nd_gen
    data:
      num_repeats: 1
      delay_secs: 0
      hold_secs: 0
      command: select
    alias: click SELECT button
mode: single
icon: mdi:tennis
```

If you make a script that works well enough for you, then simply use a [button override](https://github.com/PRProd/HA-Firemote#button-overrides) or make your own [custom launcher](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#launcher-button-customizations) to execute it from your Firemote.

**Comment by uspino2** [comment]
Thank you for the suggestion and the work. I'm afraid the Tennis Channel app in Apple TV does not make use of deep links. This other solution works, but since there's no way to tell whether the app is running or not, it can lead to errors. When you stream through the app and then go out of it, it looks like it keeps the stream alive in the background for a certain time, so when you relaunch the app there's no way to know if the video is playing or if you are back in the app main menu. Is there a "force quit" command available for ATV? That way the automation sequence would always be right, by closing the app first and then reopening it. Thanks!

**Comment by uspino2** [comment, marked as answer]
Ok, here's a very rudimentary solution to make sure the app is closed when you start the tuning process. First open the app, then double click Home for the app switch menu, then double click UP to close the latest opened app, then open the app again and then select the live stream (2x Down, 1x Select).  I think Delay times could be shortened a little bit, but this is more secure.

```
alias: Tune Tennis Channel
sequence:
  - service: media_player.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: media_player.apple_tv
  - service: media_player.select_source
    metadata: {}
    data:
      source: Tennis Channel
    target:
      entity_id: media_player.apple_tv
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - service: remote.send_command
    metadata: {}
    data:
      num_repeats: 2
      delay_secs: 0.2
      command: home
    target:
      entity_id: remote.apple_tv
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: remote.send_command
    metadata: {}
    data:
      num_repeats: 2
      delay_secs: 0.2
      hold_secs: 0
      command: up
    target:
      entity_id: remote.apple_tv
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: media_player.select_source
    metadata: {}
    data:
      source: Tennis Channel
    target:
      entity_id: media_player.apple_tv
  - delay:
      hours: 0
      minutes: 0
      seconds: 8
      milliseconds: 0
  - service: remote.send_command
    metadata: {}
    data:
      num_repeats: 2
      delay_secs: 0.5
      hold_secs: 0
      command: down
    target:
      entity_id: remote.apple_tv
  - service: remote.send_command
    metadata: {}
    data:
      command: select
    target:
      entity_id: remote.apple_tv
mode: single
icon: mdi:tennis

```
