### DISCUSSION TITLE
Style custom launchers to match roku remote?

### DISCUSSION THREAD

**Discussion by sdholden28** [PRProd/HA-Firemote#314] [Q&A] [answered]
I've had to create custom launchers to be able to adjust volume on my particular TV which is connected to a Roku Ultra. How can I style these custom buttons to match the roku remote? I've tried sampling the purple and setting that as the color, but there appears to be some sort of glow or highlight involved as I can't match the color exactly no matter what I do. There's also a black border around my custom launcher button it seems. The buttons in question are the volume_minus and volume_plus buttons at the bottom of the remote in the screenshot below.
![image](https://github.com/PRProd/HA-Firemote/assets/97199106/561d26a4-f03e-468d-b266-82d6909fe573)

**Comment by PRProd** [comment, marked as answer]
@sdholden28 ~

Thanks for asking!  There's a lot going on here, so I'm going to try to answer everything as thoroughly as possible.  You probably already know some of these things, but maybe not all of them.
<br><br>

### Solution Option 1:
The solution to what you are trying to do is likely as simple as this - an undocumented way to use app launchers / functions together with button overrides:
```YAML
app_launch_7: function-volume-down
app_launch_8: function-volume-up
button_overrides:
  function-volume-down-button:
    service: media_player.volume_down
    target:
      entity_id: { YOUR ENTITY NAME HERE (media_player.upstairs_playroom_...) }
  function-volume-up-button:
    service: media_player.volume_up
    target:
      entity_id: { YOUR ENTITY NAME HERE (media_player.upstairs_playroom_...) }
```
<br><br>

### Solution Option 2:
If the TV that your Roku Ultra is connected to supports CEC, then the function buttons should work without any additional YAML configuration editing.  When CEC is enabled on the TV and on your Roku Ultra, the volume signals are passed through the HDMI cable.  [More info can be found here](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#why-wont-the-volume-mute-andor-power-buttons-work-from-my-firemote-card)
<br><br>

### Color Matching
You have likely noticed that when clicking on an app launcher button, the button appears to light up.  Also, when a specific app is active on your Roku, the app button is also in a state where it appears to be lit up.  This is how that is achieved:
 - Button artwork and background colors are designed as best they can to match the brand's colors and style
 - All of the buttons have either a regular state, or a 'lit' state.  When the app is active, the 'lit' state takes affect.
 - Buttons in their regular state have a CSS filter applied: grayscale(25%) brightness(58%);
The thing you were trying to fight against was the CSS filter.  I'm not sure if it would even be possible to overcome that when dealing with these colors.  You got close though!

So why do the given solutions above work?  Well... since there is really no 'active' or 'inactive' state when it comes to functions like volume, channel, etc. I did not apply a CSS filter is not applied to those buttons, so their true colors are always displayed.  
<br><br>

I hope that all makes sense, and that it helps.  If not, let me know!

-Doug
