### DISCUSSION TITLE
Add spacing option to app launch to allow buttons to stick to their own row?

### DISCUSSION THREAD

**Discussion by sdoowo200leldls** [PRProd/HA-Firemote#323] [Ideas]
I have custom buttons to set my receiver to certain volumes. It would be great if I could force them to always appear on the same row.

![image](https://github.com/PRProd/HA-Firemote/assets/106935585/4b214cfd-1fe3-47c2-9cc1-1467b1ff84cd)

**Comment by PRProd** [comment]
Greetings @sdoowo200leldls!

This may seem like a bit of a lazy answer on my part, but wouldn't it be easier to just simply add one more launcher button between SONOS and your volume buttons?

**Comment by sdoowo200leldls** [comment]
That works too. Just slightly less visually appealing as there's a blank button and the usable buttons are off center.

I appreciate your work. This card is fantastic!

![image](https://github.com/PRProd/HA-Firemote/assets/106935585/27563e9d-7eb9-4a03-a186-95b52b913e8d)

**Reply by PRProd** [reply]
I wasn't really suggesting that you'd put in a blank button, I was more thinking that you'd have a different app shortcut or custom button that could fill that space.

Out of pure curiosity, what do you have that SONOS button doing?

**Comment by PRProd** [comment]
This could be an option too?
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/c5817e19-f272-4a8f-80ac-62ba26679375)

or maybe
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/df22006f-6755-4d2a-9240-c123d9551dba)

Is there a very specific look that you are aiming for?

**Comment by sdoowo200leldls** [comment]
The scale of my phone makes it so 4 icons fit per row. So I was just looking to have a clean 3 rows. Just wanted it to look tidy. I'm sure I can add another custom button in place of the blank.

My Sonos custom app just toggles play/pause on my Sonos speakers which are in the same room as the TV. I can't for the life of me figure out how to paste YAML and keep formatting so here's a screenshot.

![image](https://github.com/PRProd/HA-Firemote/assets/106935585/9decf4b4-81dd-42df-9015-9ec74e438795)

**Comment by PRProd** [comment]
If you use 3 backticks, then optionally type a language, then on the next line write your code, ending it with 3 more backticks on a new line like this:

````
```yaml
type: custom:firemote-card
entity: media_player.fire_tv_192_168_107_88
device_family: amazon-fire
device_type: fire_tv_4_series
compatibility_mode: default
```
````

you end up with this:
```yaml
type: custom:firemote-card
entity: media_player.fire_tv_192_168_107_88
device_family: amazon-fire
device_type: fire_tv_4_series
compatibility_mode: default
```

More info about that can be found [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by sdoowo200leldls** [comment]
Perfect, thank you.

```yaml
- friendly_name: Toggle Sonos
    label: Sonos Play/Pause
    image_path: >-
      https://upload.wikimedia.org/wikipedia/commons/2/28/Sonos_%28Unternehmen%29_logo.svg
    color: white
    background: '#ddaf63'
    service: media_player.media_play_pause
    target:
      device_id: 11b159ba43f5024f91607a83ea22d58f
```
