### DISCUSSION TITLE
Generic remote type?

### DISCUSSION THREAD

**Discussion by baudneo** [PRProd/HA-Firemote#361] [Q&A] [answered]
Maybe this is possible and I am missing how to do this but, it would be great to create a remote not bound to an entity. For people who have IR emitters a `button_overrides` remote would be great.

As an example, I have buttons setup that send a service call to send IR commands via MQTT. I tried creating a firemote using button_overrides but unfortunately I cant get it to work the way I would like it to.

Would something like this be possible? Basically, I would like to create something like an apple TV remote that is not bound to an Apple TV entity (or any other brand of remote, not bound to an entity or media player). Then I can customize what each button does and control my IR emitter using a nice UI remote. I hope I am explaining things properly.

# YAML
This is what I have tried but, when I use a button that is overridden, I get an error: `Failed to call service remote/send_command. must contain at least one of entity_id, device_id, area_id.`

```yaml
type: custom:firemote-card
entity: media_player.55_roku
device_family: apple-tv
device_type: appletv-4k-gen3
compatibility_mode: default
visible_name_text: ''
name_position: top
defaultRemoteStyle_override: ''
button_overrides:
  power-button:
    service: button.bsmt_tv_power
  volume-mute-button:
    service: button.bsmt_tv_mute
  volume-up-button:
    service: button.bsmt_tv_vol_up
  volume-down-button:
    service: button.bsmt_tv_vol_down
```

**Comment by PRProd** [comment]
Greetings @baudneo!

It's great to have you here!
<br>

>  it would be great to create a remote not bound to an entity. For people who have IR emitters a button_overrides remote would be great.

A request very similar to this one is already sitting in my to-do pile, it's [issue #305](https://github.com/PRProd/HA-Firemote/issues/305).  That is coming eventually.  I don't have an ETA for it yet.

You explained yourself perfectly!  I know exactly what you are asking for.  :smile: 
<br>

> This is what I have tried but, when I use a button that is overridden, I get an error: `Failed to call service remote/send_command. must contain at least one of entity_id, device_id, area_id.`

You are very close to making it work!  You're just missing one more required key listed in the [documentation for button overrides](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#button-overrides) -  the **target**.  When you use a service, you also have to declare where that command should be sent.
<br>

You have
```yaml
button_overrides:
  power-button:
    service: button.bsmt_tv_power
  volume-mute-button:
    service: button.bsmt_tv_mute
  volume-up-button:
    service: button.bsmt_tv_vol_up
  volume-down-button:
    service: button.bsmt_tv_vol_down
```
<br>

You just need to add something like this:
```yaml
button_overrides:
  power-button:
    service: button.bsmt_tv_power
    target:
      entity_id: {{ YOUR IR/MQTT ENTITY ID GOES HERE }}
  volume-mute-button:
    service: button.bsmt_tv_mute
    target:
      entity_id: {{ YOUR IR/MQTT ENTITY ID GOES HERE }}
  volume-up-button:
    service: button.bsmt_tv_vol_up
    target:
      entity_id: {{ YOUR IR/MQTT ENTITY ID GOES HERE }}
  volume-down-button:
    service: button.bsmt_tv_vol_down
    target:
      entity_id: {{ YOUR IR/MQTT ENTITY ID GOES HERE }}
```

If you are having some frustration trying to figure out exactly what needs to go in the **target** section and/or what to put in the **data** section (if required), a good idea is to make your command into a Home Assistant script using the script UI editor.  After testing your script to make sure it works the way you need, view the script as YAML!  If that YAML doesn't send you in the right direction, you could always use a button override to trigger that working script you made.

I hope this helps!  Please let me know!

-Doug

**Comment by baudneo** [comment, marked as answer]
Nice, thanks for the help! Got it figured with this:

```yaml
type: custom:firemote-card
entity: media_player.55_roku
device_family: apple-tv
device_type: appletv-4k-gen3
compatibility_mode: default
visible_name_text: ''
name_position: top
defaultRemoteStyle_override: ''
button_overrides:
  power-button:
    service: button.press
    target:
      entity_id: button.bsmt_tv_power
  volume-mute-button:
    service: button.press
    target:
      entity_id: button.bsmt_tv_mute
  volume-up-button:
    service: button.press
    target:
      entity_id: button.bsmt_tv_vol_up
  volume-down-button:
    service: button.press
    target:
      entity_id: button.bsmt_tv_vol_down

```
