### DISCUSSION TITLE
Regarding FAQ and Calling Scripts

### DISCUSSION THREAD

**Discussion by ronfarbernewman** [PRProd/HA-Firemote#470] [General]
Hey there! Love this project, so thank you for your hard work!

I was just reading the FAQ looking for something else when I stubbled upon [this question and answer](https://github.com/PRProd/HA-Firemote/wiki#can-firemote-controls-be-exposed-to-scripts-and-voice-commands):

> **Can Firemote controls be exposed to scripts and voice commands?**
> No. As far as I'm aware, there isn't a way to glue a card's buttons and functions to a script or voice command.

I actually didn't come across this during my initial setup of my Firemotes a few weeks ago, which is good, because I definitely used scripts on a few of my buttons, haha. But I also recall seeing "script" support in the examples within the README. Is this "no scripts" note in the FAQ a legacy limitation? If so should it be removed?

While on the topic of calling scripts, I will say the suggested way of linking a button to a script with the `script:` parameter of an individual button definition is a little limiting. I found myself wanting to pass a variable into my script as to use the same script for a few different buttons (selecting different inputs on my `media_player` entity), but could not for the life of me figure out how to pass data in. I ended up doing it by linking my button to a service – the `script.turn_on` service, like below:

```
custom_launchers:
  - friendly_name: Source Change - XBox
      label: XBox
      service: script.turn_on
      target:
        entity_id: script.family_room_universal_change_source
      data:
        variables:
          source: XBox
```

By calling scripts with the script.turn_on service, you're able to pass in data under variables and have them available in the scripts.

Is there an easier way to do this by passing in a script under `scripts:` or is this perhaps a better way for all scripts to be called? I'd be happy to suggest edits to the docs if so!

Thanks again for your work on this!
