### DISCUSSION TITLE
YouTube Video - My comments

### DISCUSSION THREAD

**Discussion by PRProd** [PRProd/HA-Firemote#517] [General]
I absolutely LOVE it when I see videos that people have posted who are using and enjoying the Firemote card!  

I recently found [this video](https://www.youtube.com/watch?v=Kp689zsvfFA), posted by [Un Friki Domotizado](https://www.youtube.com/@Unfrikidomotizado) / @Albert267

[![CARD de HACS muy interesante (FIREMOTE CARD),Home assistant.](https://img.youtube.com/vi/Kp689zsvfFA/0.jpg)](https://www.youtube.com/watch?v=Kp689zsvfFA "CARD de HACS muy interesante (FIREMOTE CARD),Home assistant.")
https://www.youtube.com/watch?v=Kp689zsvfFA

Please watch it!  It's great!  😄 

I wanted to address a few questions that he brought up in the video.  I hope that these comments can help anyone else with the same questions, or maybe create further discussion on ways that Firemote can improve in the future.
<br>
<br>

## At [6:52](https://youtu.be/Kp689zsvfFA?si=XD-BvqCr7WF6xxF5&t=412) in the video
![image](https://github.com/user-attachments/assets/409f6dcf-12ac-43ca-8299-5e7ba8f394ef)

There is no need to delete these YAML entries 
```yaml
entity: none
device_family: none
device_type: other
compatibility_mode: default
```
These are automatically and purposefully added/modified in your configuration when you selected **None / Other** from the device family section menu.  Removing them from your YAML config may cause undesired results.

I **highly recommend** taking a look at the Firemote wiki article [entity: none](https://github.com/PRProd/HA-Firemote/wiki/entity:-none) which outlines this concept.
<br>
<br>

## At [7:56](https://youtu.be/Kp689zsvfFA?si=metlmog4-bWpw4-T&t=476) in the video
![image](https://github.com/user-attachments/assets/c0345fac-5aaf-4853-9671-d37b65f16a46)

The [documentation](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#button-overrides) is correct.  You can call a script, but it's important to use the proper script name.  It can be difficult to track down the actual script name, but there are a few ways to find it.

Try this: Go to Settings -> Automations & Scenes -> Scripts -> 3 Dots -> Show Settings

![image](https://github.com/user-attachments/assets/07623740-7497-4df0-9e42-494a56c221ab)

In this menu, you'll find the actual name of your script:

![image](https://github.com/user-attachments/assets/53dd3dbe-2bd6-4b41-9bf8-23429e03bb56)

If I wanted to attach this **Switch to HDMI3** script to the mute button, I would use the actual script name in the YAML config like this:
```yaml
button_overrides:
  mute-button:
    script: switch_to_hdmi3
```

On a very rare occasion, it is actually possible for the name that appears here to still be the incorrect name.  It's strange, but I have seen it before.  If the instructions above do not solve your problem, take a look at [Issue #501](https://github.com/PRProd/HA-Firemote/issues/501) to see the steps that were used to track down that type of problem.

<br>
<br>

## At [10:48](https://youtu.be/Kp689zsvfFA?si=fDbyA7cHCHL5hTje&t=648) in the video
![image](https://github.com/user-attachments/assets/ad9da0df-1f9c-4d3c-96f5-6f90c9445cfb)

You _can_ use images on your custom launcher buttons by using the **image_path** YAML key.  In the value, you can specify a path to the image, or even encode one.  I recommend using SVG images.  

A possible option for Netflix might be
```yaml
  image_path: "https://www.logo.wine/a/logo/Netflix/Netflix-Logo.wine.svg"
```
The problem with using an external source for a logo is that you are now relying on an internet resource for your artwork.  Using an image served locally from your Home Assistant server, or [base64 encoding](https://www.base64encode.org/) a SVG image and directly putting it in your YAML are both better options.

Just for fun, try these!

```yaml
type: custom:firemote-card
entity: none
device_family: none
device_type: other
compatibility_mode: default
defaultRemoteStyle_override: ON1
custom_launchers:
  - friendly_name: Netflix
    background: white
    image_path: >-
      data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMDAgODIiIHdpZHRoPSIzMDAiIGhlaWdodD0iODEuMzg3Ij48cGF0aCBkPSJNLTIwMy4xIDc3MS40MTRjMS42NDMuMTU5IDMuMjgzLjMzIDQuOTIuNTA4bDMuNjE1LTguOTI3IDMuNDM3IDkuNzVjMS43NjMuMjIgMy41MjUuNDUyIDUuMjgyLjY5NGwtNi4wMjQtMTcuMDk2IDYuMDI3LTE0Ljg4aC01LjEwNGwtLjA1My4wNzItMy4yNTUgOC4wNC0yLjg1Ny04LjExMmgtNS4wMzlsNS4yMDMgMTQuNzYyLTYuMTUyIDE1LjE5ek0tMjA2LjkxMSA3NzEuMDY1di0yOS42MDFoLTUuMDM4djI5LjE4NmMxLjY4MS4xMjkgMy4zNjEuMjY5IDUuMDM4LjQxNU0tMjQ0Ljc0OSA3NjkuNDA5YzEuMzYgMCAyLjcxOC4wMSA0LjA3NC4wMjF2LTEwLjg3NWg2LjA1MXYtNC42MzFoLTYuMDV2LTcuODI1aDYuOTY4di00LjYzNmgtMTIuMDI2djI3Ljk1Yy4zMjcgMCAuNjU1LS4wMDQuOTgzLS4wMDRNLTI2MC4zODggNzY5LjY5MmMxLjY3Ny0uMDYgMy4zNTctLjExIDUuMDQtLjE1MXYtMjMuNDQyaDQuNzA3di00LjYzNmgtMTQuNDU2djQuNjM2aDQuNzA5djIzLjU5M3pNLTI5OC45MSA3NzIuODE0di0xNy42MzZsNS45NjMgMTYuOTIzYzEuODM0LS4yMDYgMy42NzEtLjQgNS41MTMtLjU4MnYtMzAuMDU1aC00LjgzM3YxOC4yNjdsLTYuNDM2LTE4LjI2N2gtNS4wNHYzMS45ODRoLjAzYzEuNTk3LS4yMjIgMy4xOTktLjQzMiA0LjgwMi0uNjM0TS0yNjkuOTUzIDc0Ni4wOTl2LTQuNjM2aC0xMi4wMjd2MjkuNTU0YzMuOTktLjM0NSA3Ljk5Ni0uNjM0IDEyLjAxNy0uODY5di00LjY0Yy0yLjMyNS4xMzUtNC42NDUuMjkxLTYuOTYuNDY0di03LjQxNWg2LjA1MXYtNC42MzRoLTYuMDUxdi03LjgyNGg2Ljk3ek0tMjIzLjcyMyA3NjUuMjg2di0yMy44MjNoLTUuMDU4djI4LjI0NmM0LjAyMy4xNDcgOC4wMzIuMzU0IDEyLjAyNy42MTJWNzY1LjY4Yy0yLjMxOS0uMTUtNC42NDEtLjI4LTYuOTY5LS4zOTIiIHN0eWxlPSJmaWxsOiNiODFkMjQ7ZmlsbC1vcGFjaXR5OjE7ZmlsbC1ydWxlOm5vbnplcm87c3Ryb2tlOm5vbmUiIHRyYW5zZm9ybT0ibWF0cml4KDIuNTQ0NTQgMCAwIDIuNTQ0NTQgNzcyLjg4NiAtMTg4Ni42OCkiLz48L3N2Zz4=
    service: media_player.select_source
    target:
      entity_id: media_player.samsung_q6_series_49
    data:
      source: Netflix
  - friendly_name: Disney
    label: Disney+
    background: white
    image_path: >-
      data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdib3g9IjAgMCA0MzYgMTUxIiB3aWR0aD0iNDM2IiBoZWlnaHQ9IjE1MSIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PGc+PHBhdGggc3R5bGU9InN0cm9rZTpub25lO3N0cm9rZS13aWR0aDoxO3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2UtbGluZWNhcDpidXR0O3N0cm9rZS1kYXNob2Zmc2V0OjA7c3Ryb2tlLWxpbmVqb2luOm1pdGVyO3N0cm9rZS1taXRlcmxpbWl0OjQ7ZmlsbDojMDAwO2ZpbGwtcnVsZTpub256ZXJvO29wYWNpdHk6MSIgdHJhbnNmb3JtPSJtYXRyaXgoLjQyIDAgMCAuNDIgMCAtODcuMDA0KSIgZD0iTTczNS44IDM2NS43Yy0xNC40IDMuMy01Mi4zIDUuMi01Mi4zIDUuMmwtNC44IDE1czE4LjktMS42IDMyLjctLjJjMCAwIDQuNS0uNSA1IDUuMS4yIDUuMi0uNCAxMC44LS40IDEwLjhzLS4zIDMuNC01LjEgNC4yYy01LjIuOS00MC44IDIuMi00MC44IDIuMmwtNS44IDE5LjVzLTIuMSA0LjUgMi43IDMuMmM0LjUtMS4yIDQxLjgtOC4yIDQ2LjctNy4yIDUuMiAxLjMgMTEgOC4yIDkuMyAxNC42LTIgNy44LTM5LjIgMzEuNi02MS45IDI5LjkgMCAwLTExLjkuOC0yMi0xNS4zLTkuNC0xNS4zIDMuNi00NC40IDMuNi00NC40cy01LjktMTMuNi0xLjYtMTguMWMwIDAgMi42LTIuMyAxMC0yLjlsOS4xLTE4LjlzLTEwLjQuNy0xNi42LTYuOWMtNS44LTcuMy02LjItMTAuNi0xLjgtMTIuNiA0LjctMi4zIDQ4LTEwLjIgNzcuOC05LjIgMCAwIDEwLjQtMSAxOS4zIDE3LS4xIDAgNC4zIDcuMy0zLjEgOXptLTExMi4xIDcyLjZjLTMuOCA5LTEzLjkgMTguNi0yNi40IDEyLjYtMTIuNC02LTMyLjEtNDYuMy0zMi4xLTQ2LjNzLTcuNS0xNS04LjktMTQuN2MwIDAtMS42LTIuOS0yLjYgMTMuNXMuMiA0OC4zLTYuMyA1My4zYy02LjIgNS0xMy43IDMtMTcuNi0yLjktMy41LTUuOC01LTE5LjYtMy4xLTQzLjggMi4zLTI0LjIgNy45LTUwIDE1LjEtNTguMSA3LjItOCAxMy0yLjIgMTUuMi0uMSAwIDAgOS42IDguNyAyNS41IDM0LjNsMi44IDQuN3MxNC40IDI0LjIgMTUuOSAyNC4xYzAgMCAxLjIgMS4xIDIuMi4zIDEuNS0uNC45LTguMi45LTguMnMtMy0yNi4zLTE2LjEtNzAuOWMwIDAtMi01LjYtLjYtMTAuOCAxLjMtNS4zIDYuNi0yLjggNi42LTIuOHMyMC40IDEwLjIgMzAuMiA0My40YzkuNyAzMy41IDMuMSA2My40LS43IDcyLjR6TTUyMy41IDM1M2MtMS43IDMuNC0yLjcgOC4zLTExLjMgOS42IDAgMC04Mi4zIDUuNi04Ni4yIDExLjQgMCAwLTIuOSAzLjQgMS42IDQuNCA0LjUuOSAyMy4xIDMuNCAzMi4xIDMuOSA5LjYuMSA0MiAuNCA1My42IDE0LjkgMCAwIDYuOSA2LjkgNi42IDIyLjUtLjMgMTYtMy4xIDIxLjYtOS4zIDI3LjQtNi41IDUuNC02Mi4zIDMwLjQtOTguMy04IDAgMC0xNi42LTE4LjUgNS43LTMyLjUgMCAwIDE2LjEtOS43IDU3IDEuNyAwIDAgMTIuNCA0LjUgMTEuOCA5LS43IDQuOC0xMC4yIDkuOS0yNCA5LjYtMTMuNC0uNC0yMy4yLTYuOC0yMS4zLTUuOCAxLjguNy0xNC40LTcuOC0xOS40LTItNSA1LjMtMy44IDguNiAxLjEgMTEuOSAxMi41IDcuMSA2MC44IDQuNiA3NS4yLTExLjQgMCAwIDUuNy02LjUtMy0xMS44LTguNy01LTMzLjYtOC00My4zLTguNS05LjMtLjUtNDMuOS4xLTQ4LjktOS4xIDAgMC01LTYuMi41LTIzLjggNS44LTE4LjQgNDYuMS0yNS41IDYzLjUtMjcuMSAwIDAgNDcuOS0xLjcgNTYuNyA4LjEtLjEgMCAxLjEgMi4zLS40IDUuNnptLTEzNiAxMDcuOWMtNS44IDQuMy0xOC4xIDIuNC0yMS42LTIuNC0zLjUtNC4zLTQuNy0yMS40LTQtNDguMi43LTI3LjEgMS4zLTYwLjcgNy4xLTY2IDYuMi01LjQgMTAtLjcgMTIuNCAzIDIuNiAzLjYgNS43IDcuNiA2LjQgMTYuMS42IDguNSAyLjYgNTMuMSAyLjYgNTMuMXMyLjYgNDAuMi0yLjkgNDQuNHpNNDAwIDMxNy4xYy0xNi45IDUuNi0yOC41IDMuNy0zOC4zLS41LTQuMyA3LjUtNi44IDkuOC0xMC4xIDEwLjMtNC44LjUtOS4xLTcuMi05LjktOS43LS44LTEuOS0zLjEtNS4xLS4zLTEyLjctOS42LTguNi0xMC4zLTIwLjItOC43LTI4IDIuNC05IDE4LjYtNDMuMiA2Ny45LTQ3LjIgMCAwIDI0LjEtMS44IDI4LjIgMTEuMWguN3MyMy40LjEgMjIuOSAyMC45Yy0uMyAyMC45LTI2IDQ2LjktNTIuNCA1NS44em0tNDYtNDYuM2MtNSA4LTUuMiAxMi44LTIuOSAxNi4xIDUuNy04LjcgMTYuMS0yMi40IDMxLjQtMzIuOC0xMS44IDEtMjEuNyA2LjEtMjguNSAxNi43em02OC4xLTEzLjRjLTE1LjUgMi4zLTM5LjUgMjMuMS01MC45IDQwLjEgMTcuNSAzLjIgNDguNCAyIDYyLjEtMjUuOS0uMSAwIDYuNS0xNy4zLTExLjItMTQuMnptNDIwLjggMTYxLjFjLTkuMyAxNi4yLTM1LjQgNTAtNzAuMiA0Mi4xLTExLjUgMjcuOS0yMS4xIDU2LTI2LjYgOTguMiAwIDAtMS4yIDguMi04IDUuMy02LjctMi40LTE3LjktMTMuNi0yMC4xLTI5LjEtMi40LTIwLjQgNi43LTU0LjkgMjUuMi05NC40LTUuNC04LjgtOS4xLTIxLjQtNS45LTM5LjMgMCAwIDQuNy0zMy4yIDM4LTYzLjIgMCAwIDQtMy41IDYuMy0yLjQgMi42IDEuMSAxLjQgMTEuOS0uNyAxNy4xLTIuMSA1LjItMTcgMzEtMTcgMzFzLTkuMyAxNy40LTYuNyAzMS4xYzE3LjUtMjYuOSA1Ny4zLTgxLjIgODItNjQuMSA4LjMgNS45IDEyLjEgMTguOCAxMi4xIDMyLjctLjEgMTIuMy0zIDI1LjMtOC40IDM1em0tNy4yLTQyLjZzLTEuNC0xMC43LTExLjggMS4xYy05IDkuOS0yNS4yIDI4LjYtMzguMyA1My45IDEzLjctMS41IDI2LjktOSAzMC45LTEyLjggNi41LTUuOCAyMS42LTIxLjQgMTkuMi00Mi4yem0tNDg1LjUgMTMuNmMtMS45IDI0LjItMTEuMiA2NC45LTc3LjEgODUtNDMuNSAxMy4xLTg0LjYgNi44LTEwNyAxLjEtLjUgOC45LTEuNSAxMi43LTIuOSAxNC4yLTEuOSAxLjktMTYuMSAxMC4xLTIzLjktMS41LTMuNS01LjUtNS4zLTE1LjUtNi4zLTI0LjQtNTAuNC0yMy4yLTczLjYtNTYuNi03NC41LTU4LjEtMS4xLTEuMS0xMi42LTEzLjEtMS4xLTI3LjggMTAuOC0xMy4zIDQ2LjEtMjYuNiA3Ny45LTMyIDEuMS0yNy4yIDQuMy00Ny43IDguMS01Ny4xIDQuNi0xMC45IDEwLjQtMS4xIDE1LjQgNi4zIDQuMiA1LjUgNi43IDI5LjIgNi45IDQ4LjEgMjAuOC0xIDMzLjEuNSA1Ni4zIDQuNyAzMC4yIDUuNSA1MC40IDIwLjkgNDguNiAzOC40LTEuMyAxNy4yLTE3LjEgMjQuMy0yMy4xIDI0LjgtNi4zLjUtMTYuMS00LTE2LjEtNC02LjctMy4yLS41LTYgNy42LTkuNSA4LjgtNC4zIDYuOC04LjcgNi44LTguNy0zLjMtOS42LTQyLjUtMTYuMy04MS41LTE2LjMtLjIgMjEuNS45IDU3LjIgMS40IDc4IDI3LjMgNS4yIDQ3LjcgNC4yIDQ3LjcgNC4yczk5LjYtMi44IDEwMi42LTY2LjRjMy4xLTYzLjctOTkuMy0xMjQuOC0xNzUtMTQ0LjItNzUuNi0xOS44LTExOC40LTYtMTIyLjEtNC4xLTQgMi0uMyAyLjYtLjMgMi42czQuMS42IDExLjIgM2M3LjUgMi40IDEuNyA2LjMgMS43IDYuMy0xMi45IDQuMS0yNy40IDEuNS0zMC4yLTQuNC0yLjgtNS45IDEuOS0xMS4yIDcuMy0xOC44IDUuNC04IDExLjMtNy43IDExLjMtNy43IDkzLjUtMzIuNCAyMDcuNCAyNi4yIDIwNy40IDI2LjJDMzM0IDMwMS41IDM1Mi4yIDM2NC45IDM1MC4yIDM4OS41ek02OCAzODYuMmMtMTAuNiA1LjItMy4zIDEyLjctMy4zIDEyLjcgMTkuOSAyMS40IDQ0LjQgMzQuOCA2Ny43IDQzLjEgMi43LTM2LjkgMi4zLTQ5LjkgMi42LTY4LjUtMzYuNCAyLjUtNTcuNCA4LjMtNjcgMTIuN3oiLz48cGF0aCBzdHlsZT0ic3Ryb2tlOm5vbmU7c3Ryb2tlLXdpZHRoOjE7c3Ryb2tlLWRhc2hhcnJheTpub25lO3N0cm9rZS1saW5lY2FwOmJ1dHQ7c3Ryb2tlLWRhc2hvZmZzZXQ6MDtzdHJva2UtbGluZWpvaW46bWl0ZXI7c3Ryb2tlLW1pdGVybGltaXQ6NDtmaWxsOiNmZmY7ZmlsbC1ydWxlOm5vbnplcm87b3BhY2l0eToxIiB0cmFuc2Zvcm09Im1hdHJpeCguNDIgMCAwIC40MiAwIC04NykiIGQ9Ik0xMDQwLjkgMzc4LjZ2MTMuMmMwIDIuOS0yLjMgNS4yLTUuMiA1LjJoLTYyLjljMCAzLjMuMSA2LjIuMSA4LjkgMCAxOS41LS44IDM1LjQtMi43IDUzLjMtLjMgMi43LTIuNSA0LjctNS4xIDQuN2gtMTMuNmMtMS40IDAtMi43LS42LTMuNi0xLjYtLjktMS0xLjQtMi40LTEuMi0zLjggMS45LTE3LjggMi44LTMzLjUgMi44LTUyLjYgMC0yLjggMC01LjctLjEtOC45aC02Mi4yYy0yLjkgMC01LjItMi4zLTUuMi01LjJ2LTEzLjJjMC0yLjkgMi4zLTUuMiA1LjItNS4yaDYxLjNjLTEuMy0yMS41LTMuOS00Mi4yLTguMS02My4yLS4yLTEuMy4xLTIuNi45LTMuNnMyLTEuNiAzLjMtMS42aDE0LjdjMi4zIDAgNC4yIDEuNiA0LjcgMy45IDQuMSAyMS43IDYuNyA0Mi44IDggNjQuNWg2My43YzIuOCAwIDUuMiAyLjQgNS4yIDUuMnoiLz48L2c+PC9zdmc+
    service: media_player.select_source
    target:
      entity_id: media_player.samsung_q6_series_49
    data:
      source: Disney+
app_launch_3: customlauncher Netflix
app_launch_4: customlauncher Disney
```
<br>
<br>

Most of the things mentioned above are also addressed in the wiki article [entity: none](https://github.com/PRProd/HA-Firemote/wiki/entity:-none) so my best recommendation is to read through that and let me know if it helps, or if anything in it is unclear.

Of course, no additional work would be required if your device was already supported by Firemote.  I just recently updated and reset the poll results in the discussion [Poll: Vote for what gets added next! #41](https://github.com/PRProd/HA-Firemote/discussions/41).  Make sure you vote again if you haven't voted since **Sep-26-2024**

I hope you find this helpful @Albert267 (and others)!  Let's keep the conversation going!  Ask your questions below!  I love to help!

-Doug
