### DISCUSSION TITLE
idea: "app launcher"

### DISCUSSION THREAD

**Discussion by ChristophCaina** [PRProd/HA-Firemote#59] [Ideas]
Hi :)
I really like the approach of rebuilding the different remote controls from the devices.
And - I also really like the option to add different 'application' buttons to the remote controller in addition to the options that are available by default.

-- I think, the customizable App Launch buttons are a major use case for most of the people here... and I already read some discussions, why it wouldn't be possible to add more app buttons to the remote controller...

So I just thought of another "Card" option... 

It would be cool, if you could have the possibility to create a "App Launch console".
A very simple remote controll design, with just a few options (back, home, enter, navigation [up, down, left, right]) - and a configurable amount of App-Buttons in addition.

It could look somehow like this mockup:
![image](https://user-images.githubusercontent.com/26391061/228172925-7ae7d707-65cb-41ea-8559-b3f0c2817996.png)

You can configure the amount of columns (1, 2, 3, 4, ...) and then, add as many app buttons as you want.
in addition to that, you could enable a specific set of fixed buttons to allow basic controll and navigation within an app.

**Comment by PRProd** [comment]
@ChristophCaina - **I LOVE THIS IDEA!!!**  That's a really great sketch too!!

Right now, I'm thinking about making this idea my next task.  Here is the priority list I have in my head right now:
 1. Complete Xiaomi Mi Box Support #55
 1.  THIS #59
 1.  Create additional Xiaomi remote options
 1.  Create option for [Amazon Fire Pro remote](https://www.amazon.com/dp/B09RX4HKTD?psc=1)
 1.  Explore other Android TV devices to include, possibly the Nokia Streaming Box #57

**Reply by ChristophCaina** [reply]
sketch-tool:
https://app.diagrams.net/ (draw.io)

**Comment by PRProd** [comment]
@ChristophCaina &  @jrspowers 
# First Look
![image](https://user-images.githubusercontent.com/25486599/229601074-a18de8f9-1a10-4bc7-9679-96a5aa604615.png)


## My Thoughts
I was thinking that since you can have more than one card pointed at the same target entity, maybe a good use case would be to have a card with ONLY app launch buttons on it that you could place alongside your standard style firemote.  

![image](https://user-images.githubusercontent.com/25486599/229604031-69dd9135-b2d4-4618-a21a-b8e76da62c42.png)

An added benefit to this style is that the number of apps is unlimited, and it can more easily fit into standard Home Assistant card spaces! 
 You may notice in this 2nd example that the number of columns has automatically changed to accommodate for the available space. 
 Adding some fixed controls to it (like the DPad, home button, back button, etc) might have to sacrifice some of this flexibility.

I can ALSO make something with a few standard controls on it (like in the example sketch) if you all think that would still be worthwhile.  Let me know!

**Reply by ChristophCaina** [reply]
Hey :)
Since launching the App isn't everything, I think some basic controls should be available.
Maybe, it would work to have them configurable (enable / disable them?)

What controls would be required for the most important actions?
I think cursor (up/down/right/left), enter...

Maybe also: Home, Back and
forward / backward... ?
Pause / Stop ?

**Reply by PRProd** [reply]
So... not a fan of my "just put 2 cards side by side" idea, eh?  :smile:

**Reply by ChristophCaina** [reply]
hm... would also be an option... sure.
But on the other hand... you would have a more "generic" keyboard that would probably fit all brands.

Having brand specific remotes could maybe cause confusion? I don't know...

**Reply by PRProd** [reply]
I just used a custom layout card, and then put two firemote cards side by side.  You could put anything in the left one.
```yaml
type: custom:layout-card
title: Fire TV
layout_type: custom:grid-layout
square: false
columns: 2
cards:
  - type: custom:firemote-card
    entity: media_player.fire_tv_192_168_107_88
    device_type: fire_tv_4_series
    compatibility_mode: default
    app_launch_1: prime-video
    app_launch_2: netflix
    app_launch_3: sky-news
    app_launch_4: youtube
    hdmi_4: Cable
    hdmi_3: Cams
    app_launch_6: ''
    app_launch_5: ''
    scale: '105'
    device_family: amazon-fire
  - type: custom:firemote-card
    entity: media_player.fire_tv_192_168_107_88
    device_family: amazon-fire
    device_type: fire_tv_4_series
    compatibility_mode: default
    defaultRemoteStyle_override: AL1
    app_launch_1: amc-plus
    app_launch_2: app-opener
    app_launch_3: apple-tv
    app_launch_4: bbc-iplayer
    app_launch_5: bell-fibe-tv
    app_launch_6: cnn
    app_launch_7: crave-tv
    app_launch_8: cyberghost
    app_launch_9: dazn
    app_launch_10: directv-stream
    app_launch_11: disney-plus
    app_launch_12: emby
    app_launch_13: espn
    app_launch_14: freevee
    app_launch_15: hbo-max
    app_launch_16: hulu
    app_launch_20: magenta-tv
    app_launch_19: kodi
    app_launch_18: jellyfin
    app_launch_17: ipvanish
    scale: '100'
    app_launch_21: myCanal
    app_launch_22: netflix
    app_launch_23: news
    app_launch_24: nordvpn
    app_launch_25: now-tv
    app_launch_26: oqee-by-free
    app_launch_27: pandora
    app_launch_28: paramount-plus
    app_launch_29: plex
    app_launch_30: prime-video
    app_launch_31: raiplay
    app_launch_32: shophq
    app_launch_33: showtime
    app_launch_34: sky-news
    app_launch_35: smart-tube-next
    app_launch_36: smart-tube-next-beta
    app_launch_37: spotify
    app_launch_38: starz
    app_launch_39: stremio
    app_launch_40: surfshark-vpn
    app_launch_66: hdmi_4
    hdmi_1: Mi Box S
    hdmi_2: Shield
    hdmi_3: Cams
    hdmi_4: Cable
    app_launch_65: hdmi_3
    app_launch_64: hdmi_2
    app_launch_63: hdmi_1
    app_launch_41: telenet-tv
    app_launch_42: tennis-channel
    app_launch_43: threenow
    app_launch_44: tivimate
    app_launch_45: tubi
    app_launch_46: tvnz-plus
    app_launch_47: twitch
    app_launch_48: vlc
    app_launch_49: waipuTV
    app_launch_50: xfinityStream
    app_launch_51: youtube
    app_launch_52: youtubekids
    app_launch_53: youtubeTV
    app_launch_54: zattoo
    app_launch_55: function-app-switch
    app_launch_56: function-mute
    app_launch_57: function-reboot
layout:
  grid-template-columns: 1fr auto
```

**Reply by jrspowers** [reply]
> I just used a custom layout card, and then put two firemote cards side by side.  You could put anything in the left one.
> 
> ```yaml
> 
> type: custom:layout-card
> 
> title: Fire TV
> 
> layout_type: custom:grid-layout
> 
> square: false
> 
> columns: 2
> 
> cards:
> 
>   - type: custom:firemote-card
> 
>     entity: media_player.fire_tv_192_168_107_88
> 
>     device_type: fire_tv_4_series
> 
>     compatibility_mode: default
> 
>     app_launch_1: prime-video
> 
>     app_launch_2: netflix
> 
>     app_launch_3: sky-news
> 
>     app_launch_4: youtube
> 
>     hdmi_4: Cable
> 
>     hdmi_3: Cams
> 
>     app_launch_6: ''
> 
>     app_launch_5: ''
> 
>     scale: '105'
> 
>     device_family: amazon-fire
> 
>   - type: custom:firemote-card
> 
>     entity: media_player.fire_tv_192_168_107_88
> 
>     device_family: amazon-fire
> 
>     device_type: fire_tv_4_series
> 
>     compatibility_mode: default
> 
>     defaultRemoteStyle_override: AL1
> 
>     app_launch_1: amc-plus
> 
>     app_launch_2: app-opener
> 
>     app_launch_3: apple-tv
> 
>     app_launch_4: bbc-iplayer
> 
>     app_launch_5: bell-fibe-tv
> 
>     app_launch_6: cnn
> 
>     app_launch_7: crave-tv
> 
>     app_launch_8: cyberghost
> 
>     app_launch_9: dazn
> 
>     app_launch_10: directv-stream
> 
>     app_launch_11: disney-plus
> 
>     app_launch_12: emby
> 
>     app_launch_13: espn
> 
>     app_launch_14: freevee
> 
>     app_launch_15: hbo-max
> 
>     app_launch_16: hulu
> 
>     app_launch_20: magenta-tv
> 
>     app_launch_19: kodi
> 
>     app_launch_18: jellyfin
> 
>     app_launch_17: ipvanish
> 
>     scale: '100'
> 
>     app_launch_21: myCanal
> 
>     app_launch_22: netflix
> 
>     app_launch_23: news
> 
>     app_launch_24: nordvpn
> 
>     app_launch_25: now-tv
> 
>     app_launch_26: oqee-by-free
> 
>     app_launch_27: pandora
> 
>     app_launch_28: paramount-plus
> 
>     app_launch_29: plex
> 
>     app_launch_30: prime-video
> 
>     app_launch_31: raiplay
> 
>     app_launch_32: shophq
> 
>     app_launch_33: showtime
> 
>     app_launch_34: sky-news
> 
>     app_launch_35: smart-tube-next
> 
>     app_launch_36: smart-tube-next-beta
> 
>     app_launch_37: spotify
> 
>     app_launch_38: starz
> 
>     app_launch_39: stremio
> 
>     app_launch_40: surfshark-vpn
> 
>     app_launch_66: hdmi_4
> 
>     hdmi_1: Mi Box S
> 
>     hdmi_2: Shield
> 
>     hdmi_3: Cams
> 
>     hdmi_4: Cable
> 
>     app_launch_65: hdmi_3
> 
>     app_launch_64: hdmi_2
> 
>     app_launch_63: hdmi_1
> 
>     app_launch_41: telenet-tv
> 
>     app_launch_42: tennis-channel
> 
>     app_launch_43: threenow
> 
>     app_launch_44: tivimate
> 
>     app_launch_45: tubi
> 
>     app_launch_46: tvnz-plus
> 
>     app_launch_47: twitch
> 
>     app_launch_48: vlc
> 
>     app_launch_49: waipuTV
> 
>     app_launch_50: xfinityStream
> 
>     app_launch_51: youtube
> 
>     app_launch_52: youtubekids
> 
>     app_launch_53: youtubeTV
> 
>     app_launch_54: zattoo
> 
>     app_launch_55: function-app-switch
> 
>     app_launch_56: function-mute
> 
>     app_launch_57: function-reboot
> 
> layout:
> 
>   grid-template-columns: 1fr auto
> 
> ```

hey this looks very nice so you can already use apps you want & put this nice nest on your card or you could put it under the remote for mobile use, that's a bit handy but i would go for card 2 remote with apps there  next ?  this code looks good do you also have a picture of this?

**Comment by PRProd** [comment]
Sorry @jrspowers, I didn't quite follow your questions.

> hey this looks very nice so you can already use apps you want & put this nice nest on your card or you could put it under the remote for mobile use, that's a bit handy but i would go for card 2 remote with apps there next ?

What are you asking here?  Are you saying that you'd like for me to continue on with making one that looks more like the sketch that @ChristophCaina  made?


> this code looks good do you also have a picture of this?

The YAML that I posted (and that you quoted) made the 2nd picture in my original post:
![image](https://user-images.githubusercontent.com/25486599/229630847-0c8f60f9-a588-4393-83bb-9ad951797036.png)

If you are asking if I have a picture of something like @ChristophCaina's sketch, no.  I haven't made one yet.

**Reply by jrspowers** [reply]
> Sorry @jrspowers, I didn't quite follow your questions.
> 
> 
> 
> > hey this looks very nice so you can already use apps you want & put this nice nest on your card or you could put it under the remote for mobile use, that's a bit handy but i would go for card 2 remote with apps there next ?
> 
> 
> 
> What are you asking here?  Are you saying that you'd like for me to continue on with making one that looks more like the sketch that @ChristophCaina  made?
> 
> 
> 
> 
> 
> > this code looks good do you also have a picture of this?
> 
> 
> 
> The YAML that I posted (and that you quoted) made the 2nd picture in my original post:
> 
> ![image](https://user-images.githubusercontent.com/25486599/229630847-0c8f60f9-a588-4393-83bb-9ad951797036.png)
> 
> 
> 
> If you are asking if I have a picture of something like @ChristophCaina's sketch, no.  I haven't made one yet.

I think the version with remote link is very good & the apps along it, but my question is whether it is also possible that the apps can come under the remote for mobile dashboard?

**Reply by PRProd** [reply]
Yes!  Arranging cards in Home Assistant can be tricky, so I like to use the custom [layout-card](https://github.com/thomasloven/lovelace-layout-card).  There might be other ways to do it, but this is how I do it.

By changing "grid-template-columns" into "grid-template-rows" part of the YAML, and tweaking the "scale" on each card, cards can be stacked vertically to look good in a mobile view:

![image](https://user-images.githubusercontent.com/25486599/229641295-0c060405-16b5-47cf-b6f2-e99acaa1da6f.png)
(scrolls vertically - not captured in the picture)

```yaml
type: custom:layout-card
title: Fire TV
layout_type: custom:grid-layout
square: false
columns: 2
cards:
  - type: custom:firemote-card
    entity: media_player.fire_tv_192_168_107_88
    device_type: fire_tv_4_series
    compatibility_mode: default
    app_launch_1: prime-video
    app_launch_2: netflix
    app_launch_3: sky-news

... removed for brevity ...

    app_launch_56: function-mute
    app_launch_57: function-reboot
layout:
  grid-template-rows: 1fr auto
```
