### ISSUE TITLE
Custom power button action

### ISSUE THREAD

**Issue by CountParadox** [PRProd/HA-Firemote#154]
**Is your feature request related to a problem? Please describe.**

I use an IR blaster to control my tv as CEC doesn't work for me. I would love to call this from the button  on the card !

**Describe the solution you'd like**

Ability to set a custom service to call on power button press

**Describe alternatives you've considered**

**Additional context**

**Comment by PRProd** [comment]
Hello @CountParadox!

You'll be happy to know that the ability to do this is already included in the current version of Firemote!

In November of 2022, [version 1.8.0](https://github.com/PRProd/HA-Firemote/releases/tag/v1.8.0) was released with new functionality which allows you to override any standard remote button with a Home Assistant script.  A few months later, In March of this year, [version 2.0.3](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.3) was released which added the ability to use the card's YAML config to send a custom service call without the need for a separate script!  Both of these options are still included in the latest version of Firemote.

Full documentation for how this works can be found in the [README.md](https://github.com/PRProd/HA-Firemote/blob/main/README.md) file under the [Button Overrides](https://github.com/PRProd/HA-Firemote#button-overrides) heading.

In your case, I would imagine that adding something like this to your Firemote card's YAML config would do the trick:
```yaml
button_overrides:
  power-button:
    service: { CHANGE THIS TO THE APPROPRIATE NAME OF YOUR IR BLASTER SERVICE CALL }
    target:
      entity_id: { CHANGE THIS TO THE ENTITY ID OF YOUR IR BLASTER }
    data:
      { YOUR PROPERTY } : { YOUR VALUE }
```
I'm unable to properly guess the exact details of your situation since I don't have your IR blaster, so everything above in between the { BRACKETS } will need to be figured out by you.  

Alternatively, you could always build a script that does what you need, and add something like this to your card's YAML config:
```yaml
button_overrides:
  power-button:
    script: { THE NAME OF YOUR SCRIPT }
```

Hopefully this answers your questions.  If not, please let me know and I'll be happy to help!

-Doug
