### ISSUE TITLE
Apple TV 4: only applications shortcuts working

### ISSUE THREAD

**Issue by EdMlt** [PRProd/HA-Firemote#230]
### Describe the bug

Hi, I just installed  the Firemote card. I can use the different shortcut I have chose but the play/pause button and the menu button not working.
When I try to use them I get a unknown error message. My configuration:
```yaml
type: custom:firemote-card
entity: media_player.sejour
device_family: apple-tv
device_type: appletv-gen4
compatibility_mode: default
apple_tv_remote_entity: remote.sejour
app_launch_1: youtube
app_launch_2: netflix
app_launch_3: disney-plus
app_launch_4: twitch
```

Maybe I didn"t install my Firemote correctly or I don't know where is the issue, any idea? Thanks

### To Reproduce

Install Firemote with an Apple TV 4 in your system

### Expected Behavior

All buttons should work but only Fav ones working

### Which Type of Device Do You Own?

Apple TV 4
