### ISSUE TITLE
Fire Tv remote button override is not working

### ISSUE THREAD

**Issue by Jaykurb** [PRProd/HA-Firemote#253]
### Describe the bug

I am trying to override the volume controls so I can control the volume from my remote. 

Using developer tools I am able to control the volume using the following services:

**Volume Down**
```YAML
service: media_player.volume_down
data: {}
target:
  entity_id: media_player.lg_webos_smart_tv
```
**Voulme Up**
```YAML
service: media_player.volume_up
data: {}
target:
  entity_id: media_player.lg_webos_smart_tv
```
**Volume Mute**
```yaml
service: media_player.volume_mute
data:
  is_volume_muted: true
target:
  entity_id: media_player.lg_webos_smart_tv
```

These all work as they should in developer tools. However, when I add these services to their respective buttons, only the mute function works. Am I missing something here, or is there a bug?

**remote config:**

```yaml
type: custom:firemote-card
entity: media_player.fire_tv_192_168_1_114
device_family: amazon-fire
device_type: fire_stick_4k
compatibility_mode: default
apple_tv_remote_entity: remote.entertainment_room_2
scale: '82'
app_launch_1: iptv-extreme-pro
app_launch_2: youtubekids
app_launch_3: ''
app_launch_4: function-next
app_launch_5: function-skip-backward
app_launch_6: function-skip-forward
app_launch_7: ''
name_position: hidden
defaultRemoteStyle_override: AF5
button_overrides:
  mute-button:
    service: media_player.volume_mute
    data:
      is_volume_muted: true
    target:
      entity_id: media_player.lg_webos_smart_tv
    volume-down-button:
      service: media_player.volume_down
      data: {}
      target:
        entity_id: media_player.lg_webos_smart_tv
    volume-up-button:
      service: media_player.volume_up
      data: {}
      target:
        entity_id: media_player.lg_webos_smart_tv
```

### To Reproduce

Use the above code with media_player.lg_webos_smart_tv

### Expected Behavior

Controls volume when respective button is pressed

### Which Type of Device Do You Own?

Fire TV stick 4k (1st gen - I think )

**Comment by PRProd** [comment]
Greetings @Jaykurb!

I edited your post a little bit so that GitHub would render your YAML code exactly the way that you posted, and I believe that the issue you are having is just a simple YAML indentation / formatting issue.  Try this instead:

```yaml
button_overrides:
  mute-button:
    service: media_player.volume_mute
    data:
      is_volume_muted: true
    target:
      entity_id: media_player.lg_webos_smart_tv
  volume-down-button:
      service: media_player.volume_down
      data: {}
      target:
        entity_id: media_player.lg_webos_smart_tv
  volume-up-button:
      service: media_player.volume_up
      data: {}
      target:
        entity_id: media_player.lg_webos_smart_tv
```
Adjusting the indentation levels of **volume-down-button** and **volume-up-button** will change the way they are interpreted.  In the code you posted, everything was a "child" under the **mute-button**.  The example here changes this simply through indentation making three parents, **mute-button**, **volume-down-button**, and **volume-up-button**
