### ISSUE TITLE
[New App Shortcut]: VivoPlay

### ISSUE THREAD

**Issue by hipur** [PRProd/HA-Firemote#279]
### App Name

VivoPlay

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

https://www.amazon.com/Vivo-Play-Favorite-Movies-Shows/dp/B089B5RNX5

### Application Details

adb_response: mSurface=Surface(name=com.tid.enjoy.firetv/com.telefonica.video.stv.launcher.LauncherActivity)/@0xc5b4c4d
  mInputMethodTarget in display# 0 Window{824fcaa u0 com.tid.enjoy.firetv/com.telefonica.video.stv.launcher.LauncherActivity}

### Optional Comments

https://play.google.com/store/apps/details?id=com.tid.enjoy&hl=en

**Comment by PRProd** [comment]
Greetings @hipur!

My apologies for the delay, the holidays can be a busy time.

Since I am in a development cycle for [Roku support](https://github.com/PRProd/HA-Firemote/discussions/275) this is not yet available in the official Firemote latest release.  However, if you'd like to use it now, it is available in the latest beta version [V3.2.0b3](https://github.com/PRProd/HA-Firemote/releases/tag/v3.2.0b3) which I have just published.

If you'd like, I can let you know when this has been published into the latest official release.

-Doug

**Comment by hipur** [comment]
Thanks! I'm on the latest beta 3.2.0b6 but couldn't enable it with the dropdown on my frontend or manually adding "vivo-play" to yaml config.

This is my config right now:
```
type: custom:firemote-card
entity: media_player.fire_tv_sala
device_family: amazon-fire
device_type: fire_tv_stick_4k_second_gen
compatibility_mode: default
defaultRemoteStyle_override: AL2
app_launcher_relative_size: '-11'
scale: '99'
app_launch_1: globoplay
app_launch_2: vivo-play
app_launch_3: tivimate
app_launch_4: smart-tube-next
```

**Comment by PRProd** [comment]
@hipur ~

If your download / update was successful, then your issue is likely being caused by a sticky cache.  I've written an article in the Firemote wiki about this very topic that you might find helpful: [Force A Refresh](https://github.com/PRProd/HA-Firemote/wiki/Force-a-Refresh)

If you are interested, you can also add the following line to your YAML config to make the current Firemote version appear in the dashboard:
```YAML
show_version_number: true
```

Here is a test config on my system that shows a nearly identical config to yours, the vivo-play app launch button, and the version number:
![image](https://github.com/PRProd/HA-Firemote/assets/25486599/d0fa1721-3704-4f29-99c5-30d8e914310e)
```YAML
type: custom:firemote-card
entity: media_player.fire_tv_192_168_107_88
device_family: amazon-fire
device_type: fire_tv_stick_4k_second_gen
compatibility_mode: default
defaultRemoteStyle_override: AL2
app_launcher_relative_size: -11
scale: '99'
app_launch_1: globoplay
app_launch_2: vivo-play
app_launch_3: tivimate
app_launch_4: smart-tube-next
```
