### ISSUE TITLE
Disney-plus app_launch dosen't work

### ISSUE THREAD

**Issue by tomerbs** [PRProd/HA-Firemote#291]
### Describe the bug

When clicking on the app_launch button the Disney+ app doesn't open, nothing is happening

### To Reproduce

Add Disney+ to the app_launch button and press on it

### Expected Behavior

Open the Disney+ app

### Which Type of Device Do You Own?

Xiaomi Mi S

### Troubleshooting Steps Completed

Tried different app_launch locations but with no success.
Youtube, Prime Video and Netflix are working.

### Additional context

This is my configuration:
```YAML
              - type: custom:firemote-card
                entity: media_player.android_tv_IP
                device_family: xiaomi
                device_type: mi-box-s
                compatibility_mode: default
                android_tv_remote_entity: remote.mibox4
                scale: '100'
                app_launch_1: youtube
                app_launch_2: disney-plus
                app_launch_3: prime-video
                app_launch_4: netflix
```
