### ISSUE TITLE
[Feature Request]: Broadlink remote

### ISSUE THREAD

**Issue by chemelli74** [PRProd/HA-Firemote#356]
### Is your feature request related to a problem?

No

### Feature Request

I would love to be able to use your fantastic work for a totally different remote/device.

I have it configured via [Broadlink Universal Remote](https://www.home-assistant.io/integrations/broadlink/)
I have already learned all the buttons call and everything works fine from a service call:

```yaml
service: remote.send_command
target:
  entity_id:
    - remote.terrazza
data:
  command: "off"
  device: Olympia Splendid Peler Tower
```

Layout is quite simple (and I'll provide a better image of course):

![IMG_8985](https://github.com/PRProd/HA-Firemote/assets/57354320/24732f33-c2bf-433e-a8ee-05b9d8c36eb6)

Thank you for considering the idea
