### ISSUE TITLE
Failed to call service media_player/select_source

### ISSUE THREAD

**Issue by Balok-Fesarius** [PRProd/HA-Firemote#442]
### Describe the bug

I believe I have Firemote installed corrected, however none of the "standard" remote buttons do anything and the application buttons return an error (Failed to call service media_player/select_source).  Please advise.

Firemote card configuration:

```
cards:
  - type: custom:firemote-card
    entity: media_player.appletv_greatroom
    device_family: apple-tv
    device_type: appletv-4k-gen3
    compatibility_mode: default
    apple_tv_remote_entity: remote.great_room
    app_launch_1: cnn
    app_launch_2: plex
    app_launch_3: youtube
    app_launch_4: max
    app_launch_5: pbs
    app_launch_6: prime-video
    visible_name_text: Great Room
    name_position: top
    button_overrides:
      mute-button:
        hidden: true
```

### To Reproduce

See description and additional context.

### Expected Behavior

Buttons should work as indicated in the instructions.

### Which Type of Device Do You Own?

Apple TV 4K (gen 3)

### Additional context

![2024-06-13_11-05-33](https://github.com/PRProd/HA-Firemote/assets/57157230/803cdbb9-c9fd-4fb7-85e7-e43871c46dd4)
![2024-06-13_11-01-23](https://github.com/PRProd/HA-Firemote/assets/57157230/1efca55e-2245-490c-b476-6300e1a25bf9)
