### ISSUE TITLE
[New App Shortcut]: btvApp

### ISSUE THREAD

**Issue by enazevedo** [PRProd/HA-Firemote#493]
### App Name

btvApp

### Device Platform

Amazon Fire

### App Store Link and/or URL to .apk file if sideloaded

http://bit.ly/btvapp213beta

### Required Information

adb_response: mSurface=Surface(name=com.mm.droid.livetv.btvapp/com.mm.droid.livetv.live.LiveNewActivity)/@0xeaa8d17
  mInputMethodTarget in display# 0 Window{cdbc19e u0 com.mm.droid.livetv.btvapp/com.mm.droid.livetv.live.LiveNewActivity}

### Optional Comments

btvApp is a third party app for LiveTV streaming

PS: Thanks for this amazing card and work!

**Comment by PRProd** [comment]
Greetings @enazevedo!

Since you asked about it [over here](https://community.home-assistant.io/t/lovelace-firemote-card-remote-controls-for-amazon-fire-android-devices/471038/173?u=crdougn), I thought that you might like to see an example for _this_ app as a [custom launcher](https://github.com/PRProd/HA-Firemote/wiki#appfunction-launcher-buttons):

```yaml
custom_launchers:
  - friendly_name: btvApp
    label: 'btvApp'
    color: '#37ddda'
    background: '#3c3939'
    action: androidtv.adb_command
    target:
      entity_id: {YOUR MEDIA PLAYER ENTITY GOES HERE}
    data:
      command: adb shell am start -n com.mm.droid.livetv.btvapp/com.mm.droid.livetv.load.LiveLoadActivity
app_launch_1: customlauncher btvApp
```
or
```yaml
custom_launchers:
  - friendly_name: btvApp
    label: 'btvApp'
    color: '#37ddda'
    background: '#3c3939'
    action: media_player.select_source
    target:
      entity_id: {YOUR MEDIA PLAYER ENTITY GOES HERE}
    data:
      source: com.mm.droid.livetv.btvapp
app_launch_1: customlauncher btvApp
```

Instead of the text, you could use an image for the button instead.  I created this SVG image that will be included when I complete your request:

![btvapp](https://github.com/user-attachments/assets/69ca0e39-47b1-4c99-93a5-6c0f93a5d1ec)
