### ISSUE TITLE
Cant get button_overrides: to work.

### ISSUE THREAD

**Issue by ChristopherJacob** [PRProd/HA-Firemote#499]
Could be a user error. (likely) but I am trying to use the AL2 remote to control a Samsung TV using the button_overrides:

I have two issues...
1. I'm receiving the error "Action andriodtv.adb_command not found"
2. I'm receiving the error at the bottom of the browser vs the pop ups described in the documentation. 

I would have thought the button_overides: would take care of item 1 and that being on the latest version would take care of item 2.

Running Version 4.0.1

I have only tried the volume up/down and mute so far.

```yaml
type: custom:firemote-card
entity: none
device_family: none
device_type: other
compatibility_mode: default
defaultRemoteStyle_override: AL2
app_launcher_relative_size: 0
button_overrides:
  mute-button:
    action: call_service
    service: remote.send_command
    service_data:
      entity_id: remote.bedroom_tv
      command: KEY_MUTE
  volume-down-button:
    action: call_service
    service: remote.send_command
    service_data:
      entity_id: remote.bedroom_tv
      command: KEY_VOLDOWN
  volume-up-button:
    action: call_service
    service: remote.send_command
    service_data:
      entity_id: remote.bedroom_tv
      command: KEY_VOLDOWN
```

**Comment by TiHiNi** [comment]
Hi,
as well a problem with `button_overrides` here.  I'm not sure if it is the same problem since I don't receive any return messesages or errors.

My config is:

```yaml
type: custom:firemote-card
entity: media_player.fire_tv_192_168_27_70
device_type: fire_tv_stick_4k_max
device_family: amazon-fire
compatibility_mode: default
app_launch_1: prime-video
app_launch_2: netflix
app_launch_3: disney-plus
app_launch_4: rtl-plus
app_launch_5: magenta-tv
scale: '82'
button_overrides:
  mute-button:
    action: media_player.volume_mute
    target:
      entity_id: media_player.samsung_6_series_55
    data:
      is_volume_muted: false
  power-button:
    hidden: true
visibility:
  - condition: state
    entity: media_player.fire_tv_192_168_27_70
    state_not: unavailable
```

The action running fine in Development -> Actions:
```yaml
action: media_player.volume_mute
target:
  entity_id: media_player.samsung_6_series_55
data:
  is_volume_muted: false
```

Versions:
HA: 2024.8.2
Firemote: 4.0.1

**Comment by PRProd** [comment]
@TiHiNi - I have just recently published an emergency release, version [v4.0.2](https://github.com/PRProd/HA-Firemote/releases/tag/v4.0.2) which should fix your issue.  Please install that new version and try again.

**Comment by TiHiNi** [comment]
@PRProd - Wow that's fast!!

It fixed the bug for me. Many thanks to you!

**Comment by PRProd** [comment]
Excellent news @TiHiNi!  I'm sorry I broke it, but I'm glad it's working properly now!  Thank you for letting me know!

**Comment by ChristopherJacob** [comment]
Damn, you move quickly. lol
Thanks for the quick turn around. 

I case anyone stumbles across this, I tried the modified yaml you suppled, but it didn't work for me...

> There is another issue here though. The YAML you wrote for your overrides didn't quite match the correct format that is outlined in the [readme](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#button-overrides). Using the example YAML you posted, this should be the proper format for your YAML.
> 
> ```yaml
> type: custom:firemote-card
> entity: none
> device_family: none
> device_type: other
> compatibility_mode: default
> defaultRemoteStyle_override: AL2
> app_launcher_relative_size: 0
> button_overrides:
>   mute-button:
>     action: remote.send_command
>     target: remote.bedroom_tv
>     data:
>       command: KEY_MUTE
>   volume-down-button:
>     action: remote.send_command
>     target: remote.bedroom_tv
>     data:
>       command: KEY_VOLDOWN
>   volume-up-button:
>     action: remote.send_command
>     target: remote.bedroom_tv
>     data:
>       command: KEY_VOLUP
> ```

What worked for me was...

```yaml
type: custom:firemote-card
entity: none
device_family: none
device_type: other
compatibility_mode: default
defaultRemoteStyle_override: AL2
app_launcher_relative_size: 0
button_overrides:
  mute-button:
    action: remote.send_command
    target:
      entity_id: remote.bedroom_tv
    data:
      command: KEY_MUTE
  volume-down-button:
    action: remote.send_command
    target:
      entity_id: remote.bedroom_tv
    data:
      command: KEY_VOLDOWN
  volume-up-button:
    action: remote.send_command
    target:
      entity_id: remote.bedroom_tv
    data:
      command: KEY_VOLUP
 ```

Now off to build out the rest! Thanks again. Amazing work!
