### ISSUE TITLE
Mute Button Script not executing for Apple TV

### ISSUE THREAD

**Issue by parchmaf** [PRProd/HA-Firemote#501]
### Describe the bug

I have button overrides configured to execute scripts on my Apple TV remote.  This works perfectly for volume up and volume down, but for the mute button, I get a error that states the script cannot be found.  If I manually run the mute script in HASS, it runs as expected.  This behavior happens on both my gen2 and gen3 Apple TV 4k.  For some reason it appears Firemote cannot find and execute the script even though it is there.

<img width="492" alt="Screenshot 2024-09-04 at 12 59 50 PM" src="https://github.com/user-attachments/assets/75641244-b425-4ef5-82ff-63e3f10ca164">

<img width="556" alt="Screenshot 2024-09-04 at 1 02 11 PM" src="https://github.com/user-attachments/assets/3e27b52d-6389-4925-a84d-7bd4efb51bb3">

### To Reproduce

Create script in HASS for muting Apple TV and assign the button override to 'mute-button'
Execute <Mute> on the Apple TV Firemote and get cannot be found error

### Expected Behavior

Script should be executed when button is pushed, therefore toggling Mute on Apple TV

### Which Type of Device Do You Own?

Apple TV 4k Gen 2 and Gen 3

### Troubleshooting Steps Completed

Manually execute script in HASS works correctly

**Comment by PRProd** [comment]
Weird!  Let's figure it out...

Could you copy/paste (not a screenshot) the YAML from your **master_bed_mute_toggle** script and the YAML from your Firemote config into this issue?  I'm hoping there is just a weird space or character out of place or something.

**Comment by parchmaf** [comment]
As requested:
<img width="751" alt="Screenshot 2024-09-04 at 4 33 20 PM" src="https://github.com/user-attachments/assets/9856ef42-4bd5-4ee0-bc83-72d718af9359">

But please keeo in mind that the specific error that I am getting is that the script cannot be found.  Strange because Firemote has no issue finding the scripts I created for volume up and down.

![IMG_0770](https://github.com/user-attachments/assets/dcabea9f-9152-4e67-836c-69d726a169c6)

**Comment by PRProd** [comment]
Since you've only sent screenshots I cannot confidently diagnose what the issue might be, but let's try one (unusual) thing.
<br>

 - In this screen, change the entity name of your working script.  I chose ``masterbedtogglemute`` as an example.
Don't forget to click UPDATE to save your changes

![image](https://github.com/user-attachments/assets/43b252d6-cf74-414f-9d8d-f17fabc5b054)
<br>

 - Next, update your Firemote YAML with the new script name, like this:
```yaml
type: custom:firemote-card
entity: media_player.master_bed_apple_tv
device_family: apple-tv
device_type: appletv-4k-gen2
compatibility_mode: default
apple_tv_remote_entity: remote.master_bed_apple_tv
scale: '100'
app_launch_1: ''
button_overrides:
  volume-down-button:
    script: master_bed_volume_down
  volume-up-button:
    script: master_bed_volume_up
  mute-button:
    script: masterbedtogglemute
```
