### ISSUE TITLE
Volume & Mute button_overrides not firing custom scripts for roku

### ISSUE THREAD

**Issue by danludwig** [PRProd/HA-Firemote#525]
### Describe the bug

Hi, I searched & read some recent issues but still am unable to work through this one. I have set up 3 scripts to perform the volume up, down and mute functions. The scripts fire `remote.send_command` actions to a specific device configured in a logitech harmony hub. Here are the scripts:

```
primary_bedroom_harmony_volume_mute:
  alias: primary_bedroom_harmony_volume_mute
  sequence:
  - action: remote.send_command
    metadata: {}
    data:
      num_repeats: 1
      delay_secs: 0.4
      hold_secs: 0
      device: Samsung Amp
      command: Mute
    target:
      entity_id: remote.primary_bedroom_harmony
  description: ''
primary_bedroom_harmony_volume_down:
  alias: primary_bedroom_harmony_volume_down
  sequence:
  - action: remote.send_command
    metadata: {}
    data:
      num_repeats: 1
      delay_secs: 0.4
      hold_secs: 0
      device: Samsung Amp
      command: VolumeDown
    target:
      entity_id: remote.primary_bedroom_harmony
  description: ''
primary_bedroom_harmony_volume_up:
  alias: primary_bedroom_harmony_volume_up
  sequence:
  - action: remote.send_command
    metadata: {}
    data:
      num_repeats: 1
      delay_secs: 0.4
      hold_secs: 0
      device: Samsung Amp
      command: VolumeUp
    target:
      entity_id: remote.primary_bedroom_harmony
  description: ''
```

I've confirmed that all 3 of these scripts do what I expect when running them from the scripts list submenu. These tell harmony to fire IR signals to a samsung soundbar connected via optical cable to the TV. HDMI-CEC and roku remote IR are not good options because the TV cannot control the soundbar power, it lacks separate power on/off functions, and only has power toggle.

### To Reproduce

Pair custom scripts like the ones above in firemote config:

```
type: custom:firemote-card
entity: media_player.primary_bedroom_roku
device_family: roku
device_type: roku-ultra-2020
compatibility_mode: default
roku_remote_entity: remote.primary_bedroom_roku
scale: "108"
visible_name_text: Primary Bedroom
app_launch_1: function-volume-down
app_launch_2: function-volume-up
app_launch_3: function-mute
app_launch_4: hulu
app_launch_5: peacock
app_launch_6: max
app_launch_7: prime-video
app_launch_8: netflix
app_launch_9: apple-tv
app_launch_10: disney-plus
button_overrides:
  power-button:
    script: primary_bedroom_harmony_toggle_power
  mute-button:
    script: primary_bedroom_harmony_volume_mute
  volume-down-button:
    script: primary_bedroom_harmony_volume_down
  volume-up-button:
    script: primary_bedroom_harmony_volume_up
  programmable-one-button:
    script: primary_bedroom_harmony_volume_down
  programmable-two-button:
    script: primary_bedroom_harmony_volume_up
```

I also have a custom script for toggle_power which works pretty well. What's interesting here is that clicking the programmable buttons to change volume do work. It's only the `Function: Volume +`, `Function: Volume -` and `Function: Mute`that do not fire the custom scripts. Instead, these seem to still be firing the default action, the same one that my physical roku remote does: changing volume and muting the TV speakers. These speakers should always be set to volume zero, with volume control on the optical-audio connected soundbar.

### Expected Behavior

Configuring `button_overrides` for `mute-button`, `volume-down-button`, and `volume-up-button` to fire custom scripts should fire said scripts instead of the default un-overridden behavior when clicking those buttons in the remote card.

### Which Type of Device Do You Own?

Roku Ultra (2020)

### Troubleshooting Steps Completed

- Attached scripts successfully to the `programmable-(one|two)-button`s in `button_overrides`. 
- Researched recent closed & unclosed issues in this repo.
- Contacted repository owner (Pending)

### Additional context

This is a pretty cool card, I really like it. Trying to make it work for my wife because the old harmony remotes freeze up or eat batteries like crazy. I was able to get a power toggle to work, and now just need the volume & mute to work before setting her up with it. Well done!

**Comment by PRProd** [comment]
Greetings @danludwig!

Thank you so much for your kind words AND for your very detailed report!  I can tell you've taken tech support calls before.  😄 

The reason that button overrides do not work in this way is because you are trying to use them to override what are actually **App Launchers**, hence the reason you find those in the App Launcher dropdown menus.  I do 100% understand how that can be a bit confusing though... sorry about not making that clearer.

The good news is that we can just make [custom launchers](https://github.com/PRProd/HA-Firemote?tab=readme-ov-file#launcher-button-customizations) to call your scripts, and they'll work the way you want them to!

Try this instead:
```yaml
custom_launchers:
  - friendly_name: Volume -
    label: vol -
    color: white
    background: "#662d91"
    script: primary_bedroom_harmony_volume_down
  - friendly_name: Volume +
    label: vol +
    color: white
    background: "#662d91"
    script: primary_bedroom_harmony_volume_up
  - friendly_name: Mute
    label: mute
    color: white
    background: "#662d91"
    script: primary_bedroom_harmony_volume_mute
app_launch_5: customlauncher Volume -
app_launch_6: customlauncher Volume +
app_launch_7: customlauncher Mute
```

Please let me know if this works for you!  I'm always happy to help!

-Doug
