### ISSUE TITLE
Some App launchers not working

### ISSUE THREAD

**Issue by msmissaert** [PRProd/HA-Firemote#547]
### Describe the bug

I configured a firemote card for my Android TV box (rpi5).
ADB and Android remote devices are correctly configured and works.
The remote works as well, only some of the app launchers give the following error :
`'Failed to perform the action media_player/select_source. required key not provided @ data['source']'`

This is shown on the interface, in the logs I can't find anything regarding this.

### To Reproduce
```yaml
type: custom:firemote-card
entity: media_player.android_tv
android_tv_remote_entity: remote.apollo5
device_family: none
device_type: other
compatibility_mode: default
defaultRemoteStyle_override: AL2
app_launcher_relative_size: 0
hide_button_group_frame: true
dpad_style: minimal
app_launch_2: go-play
app_launch_3: vtm-go
scale: "85"
```

In this example 'go-play' works. But 'vtm-go' doesn't.
Other app-launches that don't work include:
kodi
spotify
vrtmax
plex

### Expected Behavior

When app launch button is clicked the app should launch on the TV.
Only 'go-play' works. the other apps don't.

### Which Type of Device Do You Own?

Android TV Device: RPI5 with Android TV LineageOS 

### Troubleshooting Steps Completed

Tried different capitalization, but clearly that's not the issue.

Tried launching intents via ADB to load the apps and this works but would be better to have it work natively in the remote.
