### ISSUE TITLE
fire stick remote won't use Samsung button scripts

### ISSUE THREAD

**Issue by Dylon0107** [PRProd/HA-Firemote#566]
### Describe the bug

fire stick remote won't use Samsung button scripts to control volume or mute.  code editer will always add null on the end of button overrides.

### To Reproduce

button_overrides: null
mute-button:
  script: Mute
  volume-down-button:
    script: VolumeDown
  volume-up-button:
    script: VolumeUp

### Expected Behavior

volume buttons change volume and mute

### Which Type of Device Do You Own?

firestick 4k max/samsung freestyle gen 2

### Troubleshooting Steps Completed

changing script names around

**Comment by PRProd** [comment]
Greetings @Dylon0107!

This is just a simple indentation issue from what I can tell.

You posted this:
```yaml
button_overrides: null
mute-button:
  script: Mute
  volume-down-button:
    script: VolumeDown
  volume-up-button:
    script: VolumeUp
```

Try changing it to this instead:
```yaml
button_overrides:
  mute-button:
    script: Mute
    volume-down-button:
      script: VolumeDown
    volume-up-button:
      script: VolumeUp
```

That should stop your code editor from inserting ``null``, and it should cause your scripts to fire.

Please let me know if this solution fixes it for you!

-Doug
