### ISSUE TITLE
Prompted to set a button override when I already have button_overrides set 

### ISSUE THREAD

**Issue by jasonanovak** [PRProd/HA-Firemote#606]
### Describe the bug

When I press a button on a Firemote Card that has been programmed with a button override, I get prompted to set it up with a button override.

The firemote-card is set up as follows:
```
          - type: custom:firemote-card
            entity: none
            device_family: none
            device_type: other
            defaultRemoteStyle_override: AR3
            app_launcher_relative_size: 0
            button_overrides:
              center-button:
                action: pyscript.call_kodi_remote
                data:
                  key_name: select
                  entity_id: media_player.kodi_sonos
```

When I press the center-button on the card, I get an in-browser alert dialog that says:
> "center-button"
>
> Use a button override to program this button
> https://github.com/PRProd/HA-Firemote/#button-overrides

I'm not sure why my yaml configuration of the button_overrides is wrong and resulting in the alert dialog.

### To Reproduce

Set up firemote card as described above and try to press center button.

### Expected Behavior

When pressing the center button on the firemote-card, the action `pyscript.call_kodi_remote` called with data:
```
key_name: select
entity_id: media_player.kodi_sonos
````

### Which Type of Device Do You Own?

This is set up for 
```
entity: none
device_family: none
device_type: other
```

**Comment by PRProd** [comment]
Greetings @jasonanovak!

At first glance, I would say that the issue is that you are missing the "target:" key in your YAML.  Upon a second look, I'm not sure I understand what `action: pyscript.call_kodi_remote` does.  I do not have any actions in my setup that are prefixed with "pyscript".

Could you enlighten me?

-Doug

**Comment by jasonanovak** [comment]
Hi @PRProd!  Thanks for the prompt response.

pyscript is an HACS integration that lets you write custom python for HomeAssistant -- https://github.com/custom-components/pyscript. `pyscript.call_kodi_remote` is a service that I defined. It takes two parameters that are in the `data` block and I can call it successfully from Developer Tools -> Actions.

For sake of completeness/debugging, I added a `target:` to my YAML as follows:
```
button_overrides:
  center-button:
    action: pyscript.call_kodi_remote
    data:
      key_name: select
      entity_id: media_player.kodi_sonos
    target: 
      entity_id: media_player.kodi_sonos
```
even though `pyscript.call_kodi_remote` doesn't require it and that seems to have worked.

My takeaway is that button_overrides always expects there to be an action+data+target tuple even if the action doesn't require it?

Interesting when I tried to make the target null, I got this error:
```
2024-12-30 16:16:27.802 ERROR (MainThread) [frontend.js.modern.202411278] Uncaught error from Brave 131.0.0.0 on Linux x86_64
TypeError: Cannot convert undefined or null to object
getCustomServiceArgs (/hacsfiles/HA-Firemote/HA-Firemote.js:5849:29)
FiremoteCard.buttonDown (/hacsfiles/HA-Firemote/HA-Firemote.js:5875:38)
handleEvent (/hacsfiles/HA-Firemote/lit/lit-all.min.js/lit-html/src/lit-html.ts:2003:28)
```

**Comment by PRProd** [comment]
Yes!  You are correct!  Firemote expects a target since all other "built-in" integrations (not HACS) expect it as a parameter.

I won't be updating the Firemote card for this one exception since you have something that works now, and because the [pyscript](https://github.com/custom-components/pyscript) component is a community provided one.

Please let me know if you have any other questions!  I'm happy to help!

-Doug

**Comment by majorsl** [comment]
I realize this issue is closed, but wanted to say "thank you" because I faced the same issue with my LG TV as a media player and mapping a few buttons.  It also is expecting the same format as the pyscript.  Adding an extra target: fixed it right up.  Here is an example if someone similarily searches for a solution:

```
  settings-button:
    action: webostv.button
    data:
      button: MENU
      entity_id: media_player.living_room_tv
    target:
      entity_id: media_player.living_room_tv
```
