### ISSUE TITLE
Foxtel Shortcut doesnt launch on Chromecast 4K

### ISSUE THREAD

**Issue by craigmate** [PRProd/HA-Firemote#620]
### Describe the bug

HI.
I have the latest version of the Lovelace card, and have setup the Foxtel shortcut, which was released it late November.
However, when I select the button, nothing happens, other buttons (Netflix, Disney+) work without issue

However, when I select the app on the tv, it shows it highlighted within the card,

Also, I have tested I can launch it with the within the services with the below command and it appears to work
```yaml
target:
  entity_id: remote.living_room_android_tv
data:
  activity: au.com.foxtel.atv
action: remote.turn_on
```

SO, I am unsure why it doesn't work.  If you can tell me how to get some logs, I can provide them.

### To Reproduce

Running the command
```yaml
 target:
  entity_id: remote.living_room_android_tv
data:
  activity: au.com.foxtel.atv
action: remote.turn_on
```
appears to work.. 

### Expected Behavior

Launch the foxtel app successfully...

### Which Type of Device Do You Own?

Chromecast 4K

### Troubleshooting Steps Completed

I have run it successfully via the actions page.
