### ISSUE TITLE
[New Device Support]: Fire TV - 3rd Gen (2017)

### ISSUE THREAD

**Issue by PlayedIn** [PRProd/HA-Firemote#64]
### Device Name

Fire TV - 3rd Gen (2017)

### Which compatability mode event number works BEST with your device?

event3

### Additional Comments (optional)

Of those event numbers, only event3 works for some of the buttons.   The following buttons work:
The directional navigation buttons (left, right, up, down).   The options button (hamburger menu) works.  The home button works, and the return button (button with a curved arrow pointing left) works.   When playing video, the play/pause works and rewind works.

The following buttons do not work.
The center of the direction pad (select button) does not work.  When playing video, the fast forward does not work. 

If instead of an event, I choose Strong (Slow), every button works albeit slowly as expected.

### Interrogation ADB Response (optional but EXTREMELY helpful)

When I ran the ADB command as:
```
service: androidtv.adb_command
data:
  command: " adb shell dumpsys input"
target:
  entity_id: media_player.fire_tv_192_168_1_129
```
I only get the following for the entity:
adb_response: /system/bin/sh: adb: not found
