### ISSUE TITLE
Shortcuts Failing

### ISSUE THREAD

**Issue by samuelbenzaquen** [PRProd/HA-Firemote#78]
### Describe the bug

Getting the below error when pushing the apple-tv and prime-video shortcuts, I have 4 other shortcuts working just fine

Failed to call service media_player/select_source. required key not provided @ data['source']

### To Reproduce

YAML

            - type: :firemote-card
              entity: media_player.fire_cube_livingroom
              device_type: fire_tv_stick_4k_max
              compatibility_mode: event4
              app_launch_1: plex
              app_launch_2: netflix
              app_launch_3: hbo-max
              app_launch_4: apple-tv
              app_launch_5: prime-video
              app_launch_6: disney-plus

### Expected Behavior

Go to app

### Which Type of Device Do You Own?

fire_tv_stick_4k_max

### Troubleshooting Steps Completed

Reinstalled
Changed the order of the shurtcuts

### Additional context

It all worked a few days ago

**Comment by PRProd** [comment]
Hello @samuelbenzaquen!  Thanks for reaching out to me!

Thank you for also posting your YAML config for your Firemote Card, because I'm pretty sure that if we make a few changes there, we can get you going again.


Given this config that you posted: 
```yaml
type: :firemote-card
entity: media_player.fire_cube_livingroom
device_type: fire_tv_stick_4k_max
compatibility_mode: event4
app_launch_1: plex
app_launch_2: netflix
app_launch_3: hbo-max
app_launch_4: apple-tv
app_launch_5: prime-video
app_launch_6: disney-plus
```
I want to walk through a few things that I see right away, ask a few questions, and then offer a few quick solutions for you.
<br><br>
### Card Type
On the first line:
```yaml
type: :firemote-card
```
This declaration shouldn't work at all.  In fact, I'm a little surprised that you aren't seeing an error message that says **Unknown type encountered: :firemote-card**.  The correct way to declare this card is as follows: 
```yaml
type: custom:firemote-card
```
<br><br>
### Device Type
The next three lines each seem to conflict with each other:
```yaml 
entity: media_player.fire_cube_livingroom
device_type: fire_tv_stick_4k_max
compatibility_mode: event4
```
Your issue report indicates that you own a **[fire_tv_stick_4k_max](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max---1st-Gen-(2021))** yet the name of your entity contains the phrase "fire_cube" and you've set the compatibility_mode to event4, even though [event4 is the recognized mouse input](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max---1st-Gen-(2021)#device-interrogation)  for the  fire_tv_stick_4k_max.  I'm not sure what to make of this.

If you indeed do own the [fire_tv_stick_4k_max](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max---1st-Gen-(2021)), and you've somehow accidentally named your 4K Max Stick entity media_player.fire_cube_livingroom, then this is what I would recommend:
```yaml
entity: media_player.fire_cube_livingroom
device_type: fire_tv_stick_4k_max
compatibility_mode: default
```
If you think that you might have selected the wrong device type, and you're not sure which device you own, feel free to browse through the Firemote wiki page here: https://github.com/PRProd/HA-Firemote/wiki/Existing-Amazon-Devices---Support-Chart - If you need further help, please let me know.
<br><br>
### Missing Required Line
As of [Version 2.0.0](https://github.com/PRProd/HA-Firemote/releases/tag/v2.0.0) (released March 20, 2023) a new required YAML parameter was added and [documented](https://github.com/PRProd/HA-Firemote#yaml-card-setup-options) in the [README.MD](https://github.com/PRProd/HA-Firemote#readme) file:
| Name             | Type   | Required | Options                                                       | Description                            |
| -----------         | ------ | -------- | ------------------------------------------------------------- | -------------------------------------- |
| device_family | string | yes      | amazon-fire<br>nvidia-shield<br>xiaomi | Manufacturer Family                    |

If you own the [fire_tv_stick_4k_max](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max---1st-Gen-(2021)) or any other amazon stick/cube device, you'll want to add this line:
```yaml
device_family: amazon-fire
```
<br><br>
## My Questions Back To You
1. Which device model do you actually own?
2. Did you change the settings because you wanted to use a different remote style than what your device uses as its default?  If so, you might want to [take a look at this](https://github.com/PRProd/HA-Firemote#yaml-card-setup-options) and find the defaultRemoteStyle_override row.
3. Do you use only YAML to configure your dashboards, or do you also feel comfortable using the UI?
4. When you Reinstalled, did you also try to rebuild your card config from scratch, or did you use the one that you already had in place?
<br><br>
## Possible Solutions

Option 1:
The quickest way to resolve all of your issues is to use the GUI to configure a new card.  Simply [create a new Firemote Card](https://github.com/PRProd/HA-Firemote#how-to-use) from scratch which should only take a minute.  Doing this will ensure that you have all of the required settings, and it will also give you a good look at the new features that have been added since you last updated your Firemote version.

Option 2:
This option assumes that you have the [fire_tv_stick_4k_max](https://github.com/PRProd/HA-Firemote/wiki/Fire-TV-Stick-4K-Max---1st-Gen-(2021)) device, and you've named the entity 'media_player.fire_cube_livingroom'.  If one or both of those assumptions are false, then you will have to substitute the correct values.  

Correct your YAML config for this card to something like this:
```yaml
type: custom:firemote-card
entity: media_player.fire_cube_livingroom
device_family: amazon-fire
device_type: fire_tv_stick_4k_max
compatibility_mode: default
app_launch_1: plex
app_launch_2: netflix
app_launch_3: hbo-max
app_launch_4: apple-tv
app_launch_5: prime-video
app_launch_6: disney-plus
```
<br><br><br>
I hope that all of this helps!  Please let me know what happens when you try these things, and also feel free to ask any additional questions.  Thanks!

-Doug
