### ISSUE TITLE
[New App Shortcut]: XCIPTV PLAYER

### ISSUE THREAD

**Issue by almighty059** [PRProd/HA-Firemote#88]
### App Name

XCIPTV PLAYER

### Device Platform

NVIDIA Shield (but might be available for both)

### Is this app downloadable through you device's "store" app?

- [X] Yes

### Optional Comments

Here is the link for the app on Google Play store: [https://play.google.com/store/apps/details?id=com.nathnetwork.xciptv](https://play.google.com/store/apps/details?id=com.nathnetwork.xciptv)

Thanks for this great HA card..!!! I actually use it in a script as a pop-up that shows only on the device it's triggered from and it works great..!!!! I use on my laptop, tablet, and phone with no problems and it works way better than what I previously had. Thanks again.

```
type: custom:button-card
name: Shield Remote
icon: mdi:remote
size: 50px
tap_action:
  action: fire-dom-event
  browser_mod:
    service: script.tap_action_shield_remote_001
    data:
      browser_id: THIS
```

```
alias: Tap Action Shield Remote 001
sequence:
  - service: browser_mod.popup
    data_template:
      browser_id: "{{ browser_id }}"
      title: []
      content:
        type: custom:stack-in-card
        mode: vertical
        card_mod:
          style: |
            ha-card {
              padding: 0% !important;
              }
        cards:
          - type: custom:mod-card
            card_mod:
              style: |
                ha-card {
                    background: rgba(28,28,28,1.0);
                    }
            card:
              type: custom:firemote-card
              entity: media_player.nvidia_shield_tv
              device_family: nvidia-shield
              device_type: shield-tv-2019
              compatibility_mode: default
              scale: "90"
              app_launch_1: netflix
              app_launch_2: ds-video
              app_launch_3: function-find-my-remote
              name_position: hidden
              visible_name_text: ""
mode: single
icon: mdi:remote
```
